# -*- coding: utf-8 -*-
"""
Minna no Nihongo - Chuẩn hóa Bài 11 đến Bài 20 theo Sách Giáo Trình tiếng Việt chính thức.
"""
import json
import sys

sys.stdout.reconfigure(encoding='utf-8')

MINNA_LESSONS_11_20 = {
    # --- BÀI 11 ---
    "います［子どもが～］": "Có [con]",
    "います［日本に～］": "Ở [Nhật Bản]",
    "かかります": "Mất, tốn (thời gian, tiền bạc)",
    "休みます［会社を～］": "Nghỉ [làm, công ty]",
    "１つ": "Một cái (số đếm đồ vật)",
    "２つ": "Hai cái (số đếm đồ vật)",
    "３つ": "Ba cái (số đếm đồ vật)",
    "４つ": "Bốn cái (số đếm đồ vật)",
    "５つ": "Năm cái (số đếm đồ vật)",
    "６つ": "Sáu cái (số đếm đồ vật)",
    "７つ": "Bảy cái (số đếm đồ vật)",
    "８つ": "Tám cái (số đếm đồ vật)",
    "９つ": "Chín cái (số đếm đồ vật)",
    "１０": "Mười cái (số đếm đồ vật)",
    "いくつ": "Mấy cái, bao nhiêu cái",
    "１人": "Một người",
    "２人": "Hai người",
    "－人": "Người (hậu tố đếm người)",
    "－台": "Cái, chiếc (đếm máy móc, xe cộ)",
    "－枚": "Tờ, tấm (đếm vật mỏng như giấy, vé, áo sơ mi)",
    "－回": "Lần (đếm số lần)",
    "りんご": "Quả táo",
    "みかん": "Quả quýt",
    "サンドイッチ": "Bánh mì kẹp, sandwich",
    "カレー［ライス］": "Cơm cà ri",
    "アイスクリーム": "Kem",
    "切手": "Tem thư",
    "はがき": "Bưu thiếp",
    "封筒": "Phong bì",
    "両親": "Bố mẹ, cha mẹ",
    "兄弟": "Anh chị em",
    "兄": "Anh trai (của mình)",
    "お兄さん": "Anh trai (của người khác)",
    "姉": "Chị gái (của mình)",
    "お姉さん": "Chị gái (của người khác)",
    "弟": "Em trai (của mình)",
    "弟さん": "Em trai (của người khác)",
    "妹": "Em gái (của mình)",
    "妹さん": "Em gái (của người khác)",
    "外国": "Nước ngoài",
    "留学生": "Du học sinh",
    "クラス": "Lớp học",
    "－時間": "Tiếng, giờ đồng hồ",
    "－週間": "Tuần",
    "－か月": "Tháng (đếm số tháng)",
    "－年": "Năm (đếm số năm)",
    "～ぐらい": "Khoảng ~",
    "どのくらい": "Bao lâu, bao nhiêu",
    "全部で": "Tổng cộng",
    "みんな": "Tất cả, mọi người",
    "～だけ": "Chỉ ~",
    "いい［お］天気ですね。": "Thời tiết đẹp nhỉ.",
    "お出かけですか。": "Anh/chị đi ra ngoài đấy à?",
    "ちょっと ～まで。": "Tôi đi đến ~ một chút.",
    "行ってらっしゃい。": "Anh/chị đi nhé / Đi rồi về nhé (chào người đi).",
    "行って きます。": "Tôi đi đây / Tôi đi rồi về (người đi nói).",
    "行って まいります。": "Tôi xin phép đi (lịch sự).",
    "船便": "Gửi bằng đường biển",
    "航空便": "Gửi bằng đường hàng không",
    "エアメール": "Gửi bằng đường hàng không",
    "速達": "Chuyển phát nhanh",
    "書留": "Gửi bảo đảm",
    "オーストラリア": "Nước Úc",

    # --- BÀI 12 ---
    "簡単［な］": "Đơn giản, dễ dàng",
    "近い": "Gần",
    "遠い": "Xa",
    "速い、早い": "Nhanh, sớm",
    "遅い": "Chậm, muộn",
    "多い［人が～］": "Nhiều [người]",
    "少ない［人が～］": "Ít [người]",
    "暖かい、温かい": "Ấm áp, ấm",
    "涼しい": "Mát mẻ",
    "甘い": "Ngọt",
    "辛い": "Cay",
    "重い": "Nặng",
    "軽い": "Nhẹ",
    "いい［コーヒーが～］": "Thích hơn, chọn [cà phê]",
    "季節": "Mùa",
    "春": "Mùa xuân",
    "夏": "Mùa hè",
    "秋": "Mùa thu",
    "冬": "Mùa đông",
    "天気": "Thời tiết",
    "雨": "Mưa, trời mưa",
    "雪": "Tuyết, trời tuyết",
    "曇り": "Nhiều mây, trời âm u",
    "ホテル": "Khách sạn",
    "空港": "Sân bay",
    "海": "Biển, đại dương",
    "世界": "Thế giới",
    "パーティー": "Bữa tiệc",
    "［お］祭り": "Lễ hội",
    "すき焼き": "Món lẩu Sukiyaki",
    "刺身": "Món gỏi cá sống Sashimi",
    "［お］すし": "Món Sushi",
    "てんぷら": "Món tẩm bột chiên Tempura",
    "豚肉": "Thịt lợn (thịt heo)",
    "とり肉": "Thịt gà",
    "牛肉": "Thịt bò",
    "レモン": "Quả chanh",
    "生け花": "Nghệ thuật cắm hoa Ikebana",
    "紅葉": "Lá đỏ mùa thu, lá phong",
    "どちら": "Bên nào, cái nào (trong hai cái)",
    "どちらも": "Cả hai bên, cả hai",
    "いちばん": "Nhất (so sánh hơn nhất)",
    "ずっと": "Hơn hẳn, suốt",
    "初めて": "Lần đầu tiên",
    "ただいま。": "Tôi đã về đây! (khi về đến nhà)",
    "お帰りなさい。": "Anh/chị đã về đấy à! (chào người về)",
    "わあ、すごい 人ですね。": "Oa, đông người quá nhỉ!",
    "疲れました。": "Tôi mệt rồi.",
    "祇園祭": "Lễ hội Gion (Kyoto)",
    "香港": "Hồng Kông",
    "シンガポール": "Singapore",
    "すごいですね。": "Ghê thật nhỉ / Giỏi quá nhỉ / Tuyệt quá nhỉ.",
    "でも": "Nhưng, tuy nhiên",

    # --- BÀI 13 ---
    "遊びます": "Chơi, đi chơi",
    "泳ぎます": "Bơi, bơi lội",
    "迎えます": "Đón, chào đón",
    "疲れます": "Mệt mỏi",
    "結婚します": "Kết hôn, cưới",
    "買い物します": "Mua sắm",
    "食事します": "Ăn cơm, dùng bữa",
    "散歩します［公園を～］": "Đi dạo [trong công viên]",
    "大変［な］": "Vất vả, khó khăn, nghiêm trọng",
    "欲しい": "Muốn có",
    "広い": "Rộng, rộng rãi",
    "狭い": "Chật, hẹp",
    "プール": "Bể bơi, hồ bơi",
    "川": "Con sông",
    "美術": "Mỹ thuật",
    "釣り": "Câu cá",
    "スキー": "Trượt tuyết",
    "週末": "Cuối tuần",
    "［お］正月": "Tết (Tết dương lịch)",
    "～ごろ": "Khoảng chừng ~ (thời gian)",
    "何か": "Cái gì đó",
    "どこか": "Ở đâu đó",
    "のどが かわきます": "Khát nước",
    "おなかが すきます": "Đói bụng",
    "そう しましょう。": "Nhất trí làm như thế đi!",
    "ご注文は？": "Quý khách muốn gọi món gì ạ?",
    "定食": "Cơm suất, set ăn",
    "牛どん": "Cơm thịt bò Gyudon",
    "［少々］お待ち ください。": "Xin quý khách vui lòng đợi [một chút].",
    "別々に": "Riêng ra, riêng từng người",
    "出します［手紙を～］": "Gửi [thư]",
    "入ります［喫茶店に～］": "Vào [quán cà phê]",
    "出ます［喫茶店を～］": "Rời khỏi, ra khỏi [quán cà phê]",
    "寂しい": "Buồn, cô đơn",
    "市役所": "Ủy ban nhân dân thành phố, tòa thị chính",
    "経済": "Kinh tế",
    "登録": "Đăng ký",
    "おなかが いっぱいです。": "Tôi no rồi.",
    "ロシア": "Nước Nga",

    # --- BÀI 14 ---
    "つけます": "Bật (đèn, điện máy)",
    "消します": "Tắt (đèn, điện máy)",
    "開けます": "Mở (cửa)",
    "閉めます": "Đóng (cửa)",
    "急ぎます": "Vội, gấp",
    "待ちます": "Đợi, chờ",
    "持ちます": "Cầm, mang, giữ",
    "取ります": "Lấy (cho ai cái gì)",
    "手伝います": "Giúp đỡ (công việc)",
    "呼びます": "Gọi (taxi, tên)",
    "話します": "Nói chuyện",
    "使います": "Sử dụng, dùng",
    "止めます": "Dừng, đỗ (xe)",
    "見せます": "Cho xem, cho nhìn",
    "教えます［住所を～］": "Chỉ, cho biết [địa chỉ]",
    "座ります": "Ngồi",
    "立ちます": "Đứng dậy, đứng",
    "降ります［雨が～］": "Rơi, đổ [mưa rơi]",
    "コピーします": "Photo, sao chép",
    "エアコン": "Máy điều hòa không khí",
    "パスポート": "Hộ chiếu",
    "名前": "Tên, họ tên",
    "住所": "Địa chỉ",
    "地図": "Bản đồ",
    "塩": "Muối",
    "砂糖": "Đường",
    "問題": "Câu hỏi, vấn đề",
    "答え": "Câu trả lời",
    "読み方": "Cách đọc",
    "～方": "Cách ~ (cách làm gì)",
    "まっすぐ": "Thẳng, đi thẳng",
    "ゆっくり": "Chậm rãi, thong thả",
    "すぐ": "Ngay lập tức",
    "また": "Lại, hẹn gặp lại",
    "あとで": "Lát nữa, sau",
    "もう 少し": "Thêm một chút nữa",
    "もう ～": "Thêm ~ nữa",
    "さあ": "Nào, thôi nào (khuyến khích hành động)",
    "あれ？": "Ơ? Ô kìa? (ngạc nhiên)",
    "信号を 右へ 曲がって ください。": "Xin hãy rẽ phải ở cột đèn giao thông.",
    "これで お願いします。": "Xin gửi khoản này (khi trả tiền).",
    "お釣り": "Tiền thối lại, tiền thừa",
    "曲がります［右へ～］": "Rẽ [sang phải]",
    "始めます": "Bắt đầu",
    "いいですよ。": "Được chứ, đồng ý thôi.",

    # --- BÀI 15 ---
    "置きます": "Đặt, để",
    "作ります、造ります": "Làm, chế tạo, sản xuất",
    "売ります": "Bán",
    "知ります": "Biết",
    "住みます": "Sống, cư trú",
    "研究します": "Nghiên cứu",
    "資料": "Tài liệu, tư liệu",
    "カタログ": "Cuốn giới thiệu sản phẩm, catalo",
    "時刻表": "Bảng giờ tàu chạy, lịch trình",
    "服": "Quần áo",
    "製品": "Sản phẩm",
    "ソフト": "Phần mềm máy tính",
    "電子辞書": "Từ điển điện tử",
    "高校": "Trường cấp 3, trung học phổ thông",
    "歯医者": "Nha sĩ, bác sĩ nha khoa",
    "独身": "Độc thân",
    "思い出す": "Nhớ lại, hồi tưởng",
    "思い出します": "Nhớ lại, hồi tưởng",
    "いらっしゃいます": "Có, ở (Kính ngữ của います)",
    "知って います": "Biết",
    "住んで います［大阪に～］": "Đang sống [ở Osaka]",
    "専門": "Chuyên môn, ngành học",
    "床屋": "Tiệm cắt tóc (nam)",
    "プレイガイド": "Đại lý bán vé ca nhạc kịch",
    "特に": "Đặc biệt là",
    "ご家族": "Gia đình (của người khác)",

    # --- BÀI 16 ---
    "乗ります［電車に～］": "Lên [tàu điện]",
    "降ります［電車を～］": "Xuống [tàu điện]",
    "乗り換えます": "Chuyển tàu, đổi xe",
    "浴びます［シャワーを～］": "Tắm [vòi hoa sen]",
    "入れます": "Cho vào, bỏ vào",
    "出します": "Lấy ra, nộp, gửi",
    "下ろします［お金を～］": "Rút [tiền]",
    "入ります［大学に～］": "Vào [đại học]",
    "出ます［大学を～］": "Tốt nghiệp [đại học]",
    "押します": "Bấm, ấn, đẩy",
    "見学します": "Tham quan học tập",
    "電話します": "Gọi điện thoại",
    "若い": "Trẻ, trẻ trung",
    "長い": "Dài",
    "短い": "Ngắn",
    "明るい": "Sáng sủa, tươi sáng",
    "暗い": "Tối tăm, u ám",
    "体": "Cơ thể, thân thể",
    "頭": "Đầu, đầu óc",
    "髪": "Tóc",
    "顔": "Khuôn mặt",
    "目": "Mắt",
    "耳": "Tai",
    "鼻": "Mũi",
    "口": "Miệng",
    "歯": "Răng",
    "おなか": "Bụng",
    "足": "Chân, bàn chân",
    "背": "Lưng, chiều cao",
    "サービス": "Dịch vụ, phục vụ",
    "ジョギング": "Chạy bộ thể dục",
    "シャワー": "Vòi hoa sen",
    "緑": "Màu xanh lá cây",
    "［お］寺": "Ngôi chùa (Phật giáo)",
    "神社": "Đền thờ Thần đạo",
    "－番": "Số - (số thứ tự)",
    "どうやって": "Làm thế nào, bằng cách nào",
    "［いいえ、］まだまだです。": "[Không,] tôi còn kém lắm (khiêm tốn khi được khen).",
    "お引き出しですか。": "Quý khách muốn rút tiền ạ?",
    "まず": "Trước tiên, trước hết",
    "次に": "Tiếp theo",
    "キャッシュカード": "Thẻ rút tiền ngân hàng, thẻ ATM",
    "暗証番号": "Mã PIN, mã số bí mật",
    "金額": "Số tiền",
    "確認": "Xác nhận",
    "ボタン": "Nút bấm, khuy áo",
    "雪祭り": "Lễ hội tuyết",
    "やめます［会社を～］": "Nghỉ việc, bỏ [công ty]",
    "背が 高い": "Cao (dáng người)",
    "頭が いい": "Thông minh, sáng dạ",
    "ベトナム": "Việt Nam",
    "フエ": "Huế",

    # --- BÀI 17 ---
    "覚えます": "Nhớ, ghi nhớ",
    "忘れます": "Quên",
    "なくします": "Làm mất, đánh mất",
    "払います": "Trả tiền, thanh toán",
    "返します": "Trả lại (đồ đã mượn)",
    "出かけます": "Ra ngoài, đi ra ngoài",
    "脱ぎます": "Cởi (quần áo, giày)",
    "持って 行きます": "Mang đi, đem đi",
    "持って 来ます": "Mang đến, đem lại",
    "心配します": "Lo lắng",
    "残業します": "Làm thêm giờ, tăng ca",
    "出張します": "Đi công tác",
    "飲みます［薬を～］": "Uống [thuốc]",
    "入ります［おふろに～］": "Tắm [bồn tắm]",
    "大切［な］": "Quan trọng, quý giá",
    "大丈夫［な］": "Không sao, ổn thỏa",
    "危ない": "Nguy hiểm",
    "禁煙": "Cấm hút thuốc",
    "［健康］保険証": "Thẻ bảo hiểm [y tế]",
    "熱": "Sốt, cơn sốt",
    "病気": "Bệnh tật, ốm đau",
    "薬": "Thuốc uống",
    "［お］ふろ": "Bồn tắm",
    "上着": "Áo khoác ngoài",
    "下着": "Quần áo lót",
    "２、３日": "Vài ba ngày",
    "２、３～": "Vài ba ~",
    "～までに": "Trước ~ (chỉ hạn chót)",
    "ですから": "Vì thế, do đó",
    "どう しましたか。": "Bạn bị làm sao thế? / Có chuyện gì vậy?",
    "のど": "Họng, cổ họng",
    "［～が］痛いです。": "Tôi bị đau [ở ~].",
    "かぜ": "Cảm cúm, ốm",
    "お大事に。": "Chúc bạn mau khỏe! (nói với người ốm)",
    "出します［レポートを～］": "Nộp [báo cáo]",

    # --- BÀI 18 ---
    "できます": "Có thể làm được",
    "洗います": "Rửa, giặt",
    "弾きます": "Chơi, đánh (nhạc cụ phím, dây)",
    "歌います": "Hát",
    "集めます": "Thu thập, sưu tầm",
    "捨てます": "Vứt, bỏ đi",
    "換えます": "Đổi, hoán đổi",
    "運転します": "Lái xe",
    "予約します": "Đặt trước, hẹn trước",
    "ピアノ": "Đàn piano",
    "－メートル": "Mét",
    "現金": "Tiền mặt",
    "趣味": "Sở thích",
    "日記": "Nhật ký",
    "お祈り": "Cầu nguyện",
    "課長": "Trưởng phòng, tổ trưởng",
    "部長": "Trưởng ban, giám đốc bộ phận",
    "社長": "Giám đốc công ty",
    "動物": "Động vật",
    "馬": "Con ngựa",
    "インターネット": "Mạng Internet",
    "へえ": "Thế á! (ngạc nhiên)",
    "それは おもしろいですね。": "Hay thật đấy nhỉ!",
    "なかなか": "Mãi mà không... (đi với phủ định)",
    "ほんとうですか。": "Có thật không ạ?",
    "ぜひ": "Nhất định",
    "故郷": "Quê hương",
    "牧場": "Trang trại chăn nuôi",

    # --- BÀI 19 ---
    "登ります、上ります": "Leo, trèo lên (núi)",
    "泊まります［ホテルに～］": "Trọ lại, ở lại [khách sạn]",
    "掃除します": "Dọn dẹp vệ sinh",
    "洗濯します": "Giặt giũ",
    "なります": "Trở thành, trở nên",
    "眠い": "Buồn ngủ",
    "強い": "Mạnh mẽ, khỏe",
    "弱い": "Yếu ớt, kém",
    "練習": "Luyện tập",
    "ゴルフ": "Môn đánh gôn",
    "相撲": "Võ vật Sumo",
    "日": "Ngày",
    "調子": "Tình trạng, phong độ",
    "一度": "Một lần",
    "一度も": "Chưa từng một lần nào (đi với phủ định)",
    "だんだん": "Dần dần, từ từ",
    "もうすぐ": "Sắp sửa",
    "おかげさまで": "Nhờ trời / Ơn trời (cảm ơn khi được giúp đỡ)",
    "乾杯": "Cạn ly! Nâng ly!",
    "ダイエット": "Ăn kiêng giảm cân",
    "無理［な］": "Quá sức, không thể làm được",
    "体に いい": "Tốt cho sức khỏe",
    "調子が いい": "Tình trạng tốt, khỏe khoắn",
    "調子が 悪い": "Tình trạng xấu, mệt mỏi",
    "実は": "Thực ra là",
    "何回も": "Nhiều lần",
    "しかし": "Tuy nhiên, nhưng",
    "ケーキ": "Bánh ngọt, bánh gato",

    # --- BÀI 20 ---
    "要ります［ビザが～］": "Cần [thị thực, visa]",
    "調べます": "Tra cứu, điều tra",
    "修理します": "Sửa chữa",
    "僕": "Tớ, mình (nam giới dùng thân mật)",
    "君": "Cậu, em (gọi người dưới/bạn bè thân mật)",
    "うん": "Ừ (thể thông thường của はい)",
    "ううん": "Không (thể thông thường của いいえ)",
    "ことば": "Từ ngữ, tiếng nói, ngôn ngữ",
    "着物": "Áo Kimono truyền thống",
    "ビザ": "Thị thực, visa",
    "初め": "Ban đầu, lúc đầu",
    "終わり": "Kết thúc, hết",
    "こっち": "Phía này (thân mật của こちら)",
    "そっち": "Phía đó (thân mật của そちら)",
    "あっち": "Phía kia (thân mật của あちら)",
    "どっち": "Phía nào, cái nào (thân mật của どちら)",
    "みんなで": "Tất cả mọi người cùng nhau",
    "～けど": "~ nhưng (thể thông thường của が)",
    "おなかが いっぱいです": "Tôi no rồi",
    "よかったら": "Nếu bạn thích / Nếu được thì",
    "いろいろ": "Nhiều, phong phú",
    "直します": "Sửa chữa, chỉnh sửa",
    "サラリーマン": "Người làm công ăn lương, nhân viên văn phòng",
    "物価": "Vật giá, giá cả",
    "この間": "Hôm nọ, vừa rồi, dạo gần đây",
    "国へ 帰るの？": "Cậu có về nước không?",
    "どう するの？": "Cậu định làm thế nào?",
    "どう しようかな。": "Làm thế nào bây giờ nhỉ / Tính sao đây nhỉ."
}

def clean_meaning_str(text):
    if not text:
        return ""
    import re
    t = re.sub(r"#.*$", "", text).strip()
    t = t.strip("\"'“””")
    t = t.rstrip(",").strip()
    return t

def apply_part2():
    file_path = "src/data/minna_lessons.json"
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    updated = 0
    for lesson in data:
        if 11 <= lesson.get("lesson") <= 20:
            for w in lesson.get("words", []):
                k = (w.get("kanji") or "").strip()
                kn = (w.get("kana") or "").strip()
                clean_en = clean_meaning_str(w.get("meaning_en", ""))
                w["meaning_en"] = clean_en
                # Match
                for dict_key, correct_m in MINNA_LESSONS_11_20.items():
                    if k == dict_key or kn == dict_key or k.replace(" ", "") == dict_key.replace(" ", ""):
                        w["meaning"] = correct_m
                        updated += 1
                        break

    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"-> Hoàn tất chuẩn hóa Bài 11 - 20: Cập nhật {updated} từ!")

if __name__ == "__main__":
    apply_part2()
