# -*- coding: utf-8 -*-
"""
Minna no Nihongo - Chuẩn hóa Bài 41 đến Bài 50 theo Sách Giáo Trình tiếng Việt chính thức.
"""
import json
import sys

sys.stdout.reconfigure(encoding='utf-8')

MINNA_LESSONS_41_50 = {
    # --- BÀI 41 ---
    "いただきます": "Nhận, xin nhận (Khiêm nhường ngữ của もらいます)",
    "くださいます": "Cho, tặng tôi (Tôn kính ngữ của くれます)",
    "やります": "Cho, tặng (người dưới, động vật, thực vật)",
    "上げます": "Nâng lên, giơ lên",
    "下げます": "Hạ xuống, kéo xuống",
    "親切に します": "Đối xử thân thiện, tử tế",
    "かわいい": "Đáng yêu, dễ thương",
    "珍しい": "Hiếm có, quý hiếm",
    "お祝い": "Chúc mừng, quà mừng",
    "お年玉": "Tiền mừng tuổi đầu năm, tiền lì xì",
    "［お］見舞い": "Thăm hỏi người ốm, quà thăm bệnh",
    "興味": "Hứng thú, quan tâm",
    "情報": "Thông tin, tin tức",
    "文法": "Ngữ pháp",
    "発音": "Phát âm",
    "猿": "Con khỉ",
    "えさ": "Thức ăn cho động vật, mồi",
    "おもちゃ": "Đồ chơi",
    "絵本": "Sách tranh",
    "絵はがき": "Bưu thiếp có ảnh",
    "ドライバー": "Cái tua-vít",
    "ハンカチ": "Khăn tay, khăn mùi xoa",
    "靴下": "Tất, bít tất",
    "手袋": "Găng tay, bao tay",
    "幼稚園": "Trường mẫu giáo",
    "暖房": "Hệ thống sưởi, lò sưởi",
    "冷房": "Hệ thống máy lạnh, điều hòa mát",
    "温度": "Nhiệt độ",
    "祖父": "Ông (của mình)",
    "祖母": "Bà (của mình)",
    "孫": "Cháu (của mình)",
    "お孫さん": "Cháu (của người khác)",
    "おじ": "Chú, bác, cậu (của mình)",
    "おじさん": "Chú, bác, cậu (của người khác)",
    "おば": "Cô, dì, bác gái (của mình)",
    "おばさん": "Cô, dì, bác gái (của người khác)",
    "管理人": "Người quản lý, bác bảo vệ",
    "この間": "Hôm nọ, vừa rồi, dạo gần đây",
    "ひとこと": "Đôi lời, vài lời",
    "～ずつ": "Từng ~ một (số lượng)",
    "お宅": "Nhà của anh/chị (kính ngữ của うち/いえ)",
    "どうぞ お幸せに。": "Chúc hai bạn trăm năm hạnh phúc!",
    "昔話": "Truyện cổ tích, truyện dân gian",
    "ある ～": "Một ~ nọ, có một ~",
    "いじめます": "Bắt nạt, trêu chọc",
    "かめ": "Con rùa",
    "助けます": "Cứu giúp, giúp đỡ",
    "優しい": "Hiền lành, dịu dàng, tốt bụng",
    "お姫様": "Công chúa",
    "暮らします": "Sinh sống, sống",
    "陸": "Đất liền, trên cạn",
    "煙": "Khói",
    "真っ白［な］": "Trắng toát, trắng tinh",
    "中身": "Đồ vật bên trong, nội dung",
    "バッグ": "Túi xách, cặp sách (Bag)",
    "おととし": "Năm kia",
    "申し訳 ありません。": "Tôi vô cùng xin lỗi (lịch sự).",
    "預かります": "Trông giữ, nhận cất giữ hộ",
    "先日": "Mấy hôm trước, hôm nọ",
    "助かります": "Được cứu giúp, may mắn quá",
    "楽しく": "Một cách vui vẻ",

    # --- BÀI 42 ---
    "包みます": "Gói, bọc",
    "沸かします": "Đun sôi, nấu sôi",
    "混ぜます": "Khuấy, trộn lẫn",
    "計算します": "Tính toán, làm tính",
    "並びます": "Xếp hàng",
    "丈夫［な］": "Bền chắc, khỏe mạnh",
    "弁護士": "Luật sư",
    "音楽家": "Nhạc sĩ, nhà soạn nhạc",
    "教育": "Giáo dục",
    "文化": "Văn hóa",
    "社会": "Xã hội",
    "政治": "Chính trị",
    "法律": "Pháp luật, luật pháp",
    "戦争": "Chiến tranh",
    "平和": "Hòa bình",
    "目的": "Mục đích",
    "論文": "Luận văn, bài báo khoa học",
    "楽しみ": "Niềm vui, sự mong chờ",
    "ミキサー": "Máy xay sinh tố",
    "やかん": "Ấm đun nước",
    "栓抜き": "Cái mở nắp chai",
    "缶切": "Cái mở đồ hộp",
    "缶詰": "Đồ hộp, thức ăn đóng hộp",
    "のし袋": "Phong bì đựng tiền mừng (có nơ Noshi)",
    "ふろしき": "Khăn bọc đồ Furoshiki (Nhật Bản)",
    "そろばん": "Bàn tính gẩy Soroban",
    "体温計": "Nhiệt kế y tế",
    "材料": "Nguyên liệu, vật liệu",
    "国連": "Liên Hợp Quốc",
    "出ます［ボーナスが～］": "Được phát, nhận [tiền thưởng]",
    "半分": "Một nửa",
    "ローン": "Khoản vay trả góp, tiền nợ ngân hàng",
    "カップめん": "Mì cốc, mì ly ăn liền",
    "世界初": "Đầu tiên trên thế giới",
    "めん": "Sợi mì, mì",
    "広めます": "Phổ biến rộng rãi, nhân rộng",
    "市場調査": "Khảo sát thị trường",
    "割ります": "Đập vỡ, bẻ ra",
    "注ぎます": "Rót vào, đổ nước sôi vào",
    "厚い": "Dày",
    "薄い": "Mỏng, nhạt",
    "食品": "Thực phẩm, đồ ăn",
    "調査": "Điều tra, khảo sát",
    "カップ": "Cốc, ly (Cup)",
    "～の 代わりに": "Thay cho ~, thay vì ~",
    "どこででも": "Ở bất cứ đâu",
    "今では": "Hiện nay, bây giờ",

    # --- BÀI 43 ---
    "増えます［輸出が～］": "Tăng lên [xuất khẩu tăng]",
    "減ります［輸出が～］": "Giảm đi [xuất khẩu giảm]",
    "上がります［値段が～］": "Tăng lên [giá cả tăng]",
    "下がります［値段が～］": "Giảm xuống [giá cả giảm]",
    "切れます［ひもが～］": "Đứt [sợi dây đứt]",
    "とれます［ボタンが～］": "Tuột, rơi ra [cúc áo tuột]",
    "落ちます［荷物が～］": "Rơi, rớt [hành lý rơi]",
    "なくなります［ガソリンが～］": "Hết, cạn [xăng hết]",
    "変［な］": "Kỳ lạ, khác thường",
    "幸せ［な］": "Hạnh phúc",
    "うまい": "Ngon miệng, khéo léo",
    "まずい": "Dở, không ngon",
    "つまらない": "Nhàm chán, vô vị",
    "ガソリン": "Xăng xe",
    "パンフレット": "Tờ rơi quảng cáo, tập gấp Pamphlet",
    "今にも": "Sắp sửa... đến nơi rồi",
    "ばら": "Hoa hồng",
    "ドライブ": "Lái xe ô tô đi dạo",
    "理由": "Lý do",
    "謝ります": "Xin lỗi, tạ lỗi",
    "知り合います": "Quen biết nhau",
    "センス": "Gu thẩm mỹ, khiếu cảm nhận",
    "会員": "Hội viên, thành viên",
    "適当［な］": "Phù hợp, thích hợp",
    "年齢": "Tuổi tác",
    "収入": "Thu nhập",
    "ぴったり": "Vừa khít, vừa vặn",
    "そのうえ": "Hơn nữa, thêm vào đó",
    "～と いいます": "Có tên gọi là ~",

    # --- BÀI 44 ---
    "泣きます": "Khóc",
    "笑います": "Cười",
    "眠ります": "Ngủ",
    "乾きます［シャツが～］": "Khô [áo sơ mi khô]",
    "ぬれます［シャツが～］": "Bị ướt [áo sơ mi ướt]",
    "滑ります": "Trượt, trơn trượt",
    "起きます［事故が～］": "Xảy ra [tai nạn xảy ra]",
    "調節します": "Điều chỉnh (nhiệt độ, kích thước)",
    "濃い": "Đậm đà (vị), đậm (màu), đặc (chất lỏng)",
    "空気": "Không khí",
    "涙": "Nước mắt",
    "和食": "Món ăn kiểu Nhật",
    "洋食": "Món ăn kiểu Tây",
    "御数": "Món ăn phụ, món ăn kèm (Okazu)",
    "量": "Khối lượng, lượng",
    "－倍": "Gấp - lần",
    "シングル": "Phòng đơn (khách sạn)",
    "ツイン": "Phòng đôi 2 giường (khách sạn)",
    "洗濯物": "Quần áo giặt giũ",
    "どう なさいますか。": "Quý khách muốn làm kiểu gì ạ? (thợ cắt tóc hỏi)",
    "カット": "Cắt tóc",
    "シャンプー": "Gội đầu (Shampoo)",
    "どういうふうに なさいますか。": "Quý khách muốn cắt/tạo kiểu thế nào ạ?",
    "ショート": "Cắt ngắn, kiểu tóc ngắn",
    "～みたいに して ください。": "Xin hãy làm giống như ~",
    "これで よろしいでしょうか。": "Như thế này đã được chưa ạ?",
    "［どうも］お疲れさまでした。": "Cảm ơn quý khách đã kiên nhẫn (thợ nói với khách).",
    "嫌がります": "Tỏ vẻ không thích, khó chịu",
    "順序": "Thứ tự, trình tự",
    "安心［な］": "An tâm, yên tâm",
    "表現": "Cách biểu hiện, diễn đạt",
    "別れます": "Chia tay, từ biệt",
    "これら": "Những cái này",
    "縁起が 悪い": "Xui xẻo, điềm gở",
    "丁寧［な］": "Lịch sự, cẩn thận, chu đáo",
    "細かい": "Nhỏ, chi tiết, tỉ mỉ",
    "箪笥": "Tủ quần áo có ngăn kéo",

    # --- BÀI 45 ---
    "信じます": "Tin tưởng, tin cậy",
    "キャンセルします": "Hủy bỏ (Cancel)",
    "知らせます": "Báo tin, thông báo",
    "保証書": "Giấy bảo hành",
    "領収書": "Hóa đơn, biên lai thu tiền",
    "キャンプ": "Cắm trại (Camp)",
    "中止": "Hủy bỏ, hoãn lại, đình chỉ",
    "点": "Điểm số",
    "梅": "Hoa mơ, hoa mai Ume",
    "１１０番": "Số điện thoại cảnh sát khẩn cấp (110)",
    "１１９番": "Số điện thoại cứu hỏa/cấp cứu khẩn cấp (119)",
    "無理に": "Quá sức, gượng ép",
    "楽しみに して います": "Háo hức mong chờ",
    "以上です。": "Xin hết / Đến đây là hết.",
    "係員": "Nhân viên trực ban, người phụ trách",
    "コース": "Đường chạy, tuyến đường đua",
    "スタート": "Xuất phát, khởi động (Start)",
    "－位": "Vị trí thứ -, hạng -",
    "優勝します": "Vô địch, giành giải nhất",
    "悩み": "Nỗi phiền muộn, lo âu",
    "目覚まし［時計］": "Đồng hồ báo thức",
    "鳴ります": "Kêu, reo (chuông reo)",
    "セットします": "Cài đặt (giờ báo thức)",
    "それでも": "Dù vậy, tuy nhiên",
    "贈り物": "Món quà tặng",
    "間違い電話": "Nhầm số điện thoại",
    "係": "Người phụ trách, ban phụ trách",
    "［－円］札": "Tờ tiền mệnh giá [－ yên]",
    "ちゃんと": "Chỉn chu, đâu ra đấy, nghiêm túc",

    # --- BÀI 46 ---
    "渡します": "Giao cho, đưa cho",
    "帰って 来ます": "Về, quay trở lại",
    "出ます［バスが～］": "Xuất phát, khởi hành [xe buýt]",
    "届きます［荷物が～］": "Được chuyển đến [hàng hóa]",
    "焼きます": "Nướng, rán",
    "宅配便": "Dịch vụ giao hàng tận nhà Takkyubin",
    "原因": "Nguyên nhân",
    "～の 所": "Chỗ của ~, nơi của ~",
    "半年": "Nửa năm",
    "ちょうど": "Vừa đúng, vừa vặn",
    "たった今": "Vừa mới xong tức thì",
    "今 いいですか。": "Bây giờ bạn có rảnh một lát không?",
    "ガスレンジ": "Bếp ga",
    "具合": "Tình trạng, trạng thái",
    "どちら様でしょうか。": "Xin hỏi ai ở đầu dây đấy ạ?",
    "お待たせしました。": "Xin lỗi vì đã để quý khách phải đợi lâu.",
    "向かいます": "Hướng tới, đi về phía",
    "ついて います": "May mắn, số đỏ",
    "床": "Sàn nhà",
    "転びます": "Ngã, vấp ngã",
    "ベル": "Chuông, tiếng chuông",
    "慌てて": "Vội vã, cuống cuồng",
    "順番に": "Lần lượt theo thứ tự",
    "出来事": "Sự việc, biến cố xảy ra",
    "注射": "Tiêm thuốc",
    "食欲": "Cảm giác thèm ăn, ngon miệng",
    "ステレオ": "Dàn âm thanh nổi Stereo",
    "今 いいでしょうか。": "Bây giờ tôi làm phiền anh/chị một lát có được không ạ?",
    "知識": "Kiến thức, tri thức",
    "宝庫": "Kho báu, kho tàng",
    "手に入ります［情報が～］": "Thu thập được, có được trong tay [thông tin]",
    "キーワード": "Từ khóa (Keyword)",
    "一部分": "Một phần, một bộ phận",
    "秒": "Giây (thời gian)",
    "出ます［本が～］": "Xuất bản [sách được xuất bản]",

    # --- BÀI 47 ---
    "集まります［人が～］": "Tập hợp lại, tụ tập [người tụ tập]",
    "別れます［人が～］": "Chia tay, ly biệt [người chia tay]",
    "します［音／声が～］": "Có tiếng vang lên [âm thanh/tiếng nói]",
    "します［味が～］": "Có vị",
    "します［においが～］": "Có mùi",
    "厳しい": "Nghiêm khắc, khắc nghiệt",
    "ひどい": "Tồi tệ, tàn nhẫn, khủng khiếp",
    "実験": "Thí nghiệm, thực nghiệm",
    "におい": "Mùi (hương hoặc mùi hôi)",
    "科学": "Khoa học",
    "パトカー": "Xe tuần tra cảnh sát (Patrol car)",
    "救急車": "Xe cấp cứu, cứu thương",
    "賛成": "Tán thành, đồng ý",
    "反対": "Phản đối",
    "～に よると": "Theo nguồn tin từ ~",
    "婚約します": "Đính hôn, hứa hôn",
    "どうも": "Hình như, dường như là (phán đoán)",
    "化粧": "Trang điểm, son phấn",
    "女性": "Phụ nữ, phái nữ",
    "男性": "Đàn ông, nam giới",
    "長生き": "Sống thọ, trường thọ",
    "平均寿命": "Tuổi thọ trung bình",
    "比べます［男性と～］": "So sánh [với nam giới]",
    "博士": "Tiến sĩ (học vị)",
    "脳": "Não bộ",
    "ホルモン": "Hormone nội tiết tố",
    "化粧品": "Mỹ phẩm, đồ trang điểm",
    "調べ": "Sự tìm hiểu, điều tra, nghiên cứu",

    # --- BÀI 48 ---
    "降ろします、下ろします": "Hạ xuống, bốc dỡ (hàng hóa)",
    "届けます": "Giao hàng, chuyển tới",
    "録音します": "Ghi âm, thu âm",
    "塾": "Lớp học thêm, trường luyện thi (Juku)",
    "生徒": "Học sinh (cấp 1, cấp 2)",
    "～間": "Khoảng thời gian ~",
    "お忙しいですか。": "Bác/Anh/Chị có bận không ạ?",
    "営業": "Kinh doanh, bán hàng (Sales)",
    "それまでに": "Trước thời điểm đó",
    "かまいません。": "Không sao đâu, tôi không phiền gì đâu.",
    "楽しみます": "Thưởng thức, tận hưởng",
    "親": "Bố mẹ, cha mẹ",
    "－パーセント": "Phần trăm (%)",
    "その 次": "Tiếp theo đó",
    "習字": "Luyện viết chữ đẹp (thư pháp)",
    "入管": "Cục quản lý xuất nhập cảnh (viết tắt của 出入国在留管理局)",
    "再入国ビザ": "Visa tái nhập cảnh",
    "代わりを します": "Làm thay cho, thế chỗ",
    "競走します": "Chạy đua, thi chạy",
    "サーカス": "Rạp xiếc, gánh xiếc",
    "芸": "Trò diễn xiếc, ngón nghề",
    "姿": "Dáng vẻ, điệu bộ",
    "心": "Trái tim, tấm lòng, tâm hồn",
    "とらえます": "Chiếm trọn, bắt lấy, thu hút",

    # --- BÀI 49 ---
    "勤めます［会社に～］": "Làm việc, công tác [tại công ty]",
    "掛けます［いすに～］": "Ngồi [trên ghế]",
    "過ごします": "Trải qua, dành (thời gian)",
    "いらっしゃいます": "Ở, đi, đến (Tôn kính ngữ của います, 行きます, 来ます)",
    "召し上がります": "Ăn, uống (Tôn kính ngữ của 食べます, 飲みます)",
    "おっしゃいます": "Nói, tên là (Tôn kính ngữ của 言います)",
    "なさいます": "Làm (Tôn kính ngữ của します)",
    "ご覧に なります": "Xem, nhìn (Tôn kính ngữ của 見ます)",
    "ご存じです": "Biết (Tôn kính ngữ của 知っています)",
    "旅館": "Nhà trọ kiểu Nhật Ryokan",
    "奥様": "Phu nhân, bà nhà (Tôn kính ngữ của 奥さん)",
    "たまに": "Thỉnh thoảng, đôi khi",
    "どなたでも": "Bất kỳ vị nào (Kính ngữ của だれでも)",
    "－年－組": "Lớp - niên khóa -",
    "出します［熱を～］": "Bị sốt [lên cơn sốt]",
    "よろしく お伝え ください。": "Xin hãy chuyển lời hỏi thăm của tôi đến...",
    "失礼いたします。": "Tôi xin phép ra về / Xin phép thất lễ (Khiêm nhường ngữ).",
    "経歴": "Lý lịch, quá trình làm việc",
    "医学部": "Khoa Y, trường Y",
    "目指します": "Hướng tới, nhắm tới mục tiêu",
    "進みます": "Học lên (cao học), tiến tới",
    "授賞します": "Được trao giải thưởng",
    "講演会": "Buổi diễn thuyết, hội thảo thuyết trình",
    "寄ります［銀行に～］": "Ghé tạt qua [ngân hàng]",
    "灰皿": "Gạt tàn thuốc lá",
    "貿易": "Thương mại quốc tế, mậu dịch",
    "ちっとも": "Một chút cũng không... (đi với phủ định)",
    "遠慮なく": "Xin đừng khách sáo, cứ tự nhiên",
    "講師": "Giảng viên, người thuyết giảng",
    "作品": "Tác phẩm nghệ thuật",
    "作家": "Nhà văn, tác gia",
    "～で いらっしゃいます": "Là ~ (Tôn kính ngữ của です)",
    "長男": "Con trai cả, con trai trưởng",
    "障害": "Khuyết tật, khiếm khuyết cơ thể",
    "お持ちです": "Có, sở hữu (Tôn kính ngữ của 持っています)",
    "作曲": "Soạn nhạc, sáng tác nhạc",
    "それでは": "Sau đây, tiếp theo đây",

    # --- BÀI 50 ---
    "参ります": "Đi, đến (Khiêm nhường ngữ của 行きます và 来ます)",
    "おります": "Ở, có mặt (Khiêm nhường ngữ của います)",
    "いただきます": "Ăn, uống, nhận (Khiêm nhường ngữ của 食べます, 飲みます, もらいます)",
    "申します": "Nói, tên là (Khiêm nhường ngữ của 言います)",
    "いたします": "Làm (Khiêm nhường ngữ của します)",
    "拝見します": "Xem, nhìn (Khiêm nhường ngữ của 見ます)",
    "存じます": "Biết (Khiêm nhường ngữ của 知っています/思います)",
    "伺います": "Hỏi, nghe, đến thăm (Khiêm nhường ngữ của 聞きます và 行きます)",
    "お目に かかります": "Gặp mặt (Khiêm nhường ngữ của 会います)",
    "私": "Tôi (Khiêm nhường ngữ trang trọng của わたし)",
    "さ来週": "Tuần sau nữa",
    "さ来月": "Tháng sau nữa",
    "さ来年": "Năm sau nữa",
    "緊張します": "Căng thẳng, hồi hộp",
    "賞金": "Tiền thưởng giải",
    "きりん": "Hươu cao cổ",
    "ころ": "Hồi, dạo, thời (thời trẻ con...)",
    "かないます［夢が～］": "Trở thành hiện thực [giấc mơ]",
    "応援します": "Cổ vũ, ủng hộ, tiếp sức",
    "心から": "Từ tận đáy lòng, chân thành",
    "感謝します": "Cảm tạ, biết ơn chân thành",
    "お礼": "Lời cảm ơn, quà cảm ơn",
    "お元気で いらっしゃいますか。": "Bác/Anh/Chị dạo này vẫn mạnh khỏe chứ ạ? (Kính ngữ)",
    "迷惑を かけます": "Làm phiền, gây phiền hà",
    "生かします": "Phát huy, tận dụng tối đa",
    "ございます": "Có (Lịch sự trang trọng của あります)",
    "～で ございます": "Là (Lịch sự trang trọng của です)",
    "郊外": "Khu vực ngoại ô",
    "ただ今": "Ngay bây giờ, lúc này (hiện tại)",
    "撮ります［ビデオに～］": "Quay [video]",
    "ひとこと よろしいでしょうか。": "Tôi xin phép nói đôi lời được không ạ?",
    "協力します": "Hợp tác, chung sức giúp đỡ",
    "拝啓": "Kính thư (mở đầu lá thư trang trọng)",
    "敬具": "Kính thư (cuối lá thư trang trọng)"
}

def clean_meaning_str(text):
    if not text:
        return ""
    import re
    t = re.sub(r"#.*$", "", text).strip()
    t = t.strip("\"'“””")
    t = t.rstrip(",").strip()
    return t

def apply_part5():
    file_path = "src/data/minna_lessons.json"
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    updated = 0
    for lesson in data:
        if 41 <= lesson.get("lesson") <= 50:
            for w in lesson.get("words", []):
                k = (w.get("kanji") or "").strip()
                kn = (w.get("kana") or "").strip()
                clean_en = clean_meaning_str(w.get("meaning_en", ""))
                w["meaning_en"] = clean_en
                # Match
                for dict_key, correct_m in MINNA_LESSONS_41_50.items():
                    if k == dict_key or kn == dict_key or k.replace(" ", "") == dict_key.replace(" ", ""):
                        w["meaning"] = correct_m
                        updated += 1
                        break

    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"-> Hoàn tất chuẩn hóa Bài 41 - 50: Cập nhật {updated} từ!")

if __name__ == "__main__":
    apply_part5()
