# -*- coding: utf-8 -*-
"""
Minna no Nihongo - Chuẩn hóa Bài 31 đến Bài 40 theo Sách Giáo Trình tiếng Việt chính thức.
"""
import json
import sys

sys.stdout.reconfigure(encoding='utf-8')

MINNA_LESSONS_31_40 = {
    # --- BÀI 31 ---
    "続けます": "Tiếp tục",
    "見つけます": "Tìm thấy, phát hiện ra",
    "取ります［休みを～］": "Xin nghỉ [nghỉ phép]",
    "受けます［試験を～］": "Dự thi [kỳ thi]",
    "申し込みます": "Đăng ký",
    "休憩します": "Nghỉ giải lao",
    "連休": "Kỳ nghỉ dài ngày liên tiếp",
    "作文": "Bài văn, bài tập làm văn",
    "発表": "Phát biểu, công bố",
    "展覧会": "Triển lãm",
    "結婚式": "Lễ cưới, đám cưới",
    "［お］葬式": "Đám tang, tang lễ",
    "式": "Buổi lễ, nghi thức",
    "本社": "Trụ sở chính (công ty)",
    "支店": "Chi nhánh (công ty)",
    "教会": "Nhà thờ (Thiên Chúa giáo)",
    "大学院": "Cao học, trường đào tạo sau đại học",
    "動物園": "Vườn bách thú, sở thú",
    "温泉": "Suối nước nóng Onsen",
    "帰り": "Chiều về, lúc về",
    "お子さん": "Con của người khác",
    "－号": "Số (chuyến tàu, cơn bão)",
    "～の 方": "Phía ~, hướng ~",
    "残ります": "Còn lại, sót lại",
    "入学試験": "Kỳ thi tuyển sinh đầu vào",
    "月に": "Mỗi tháng",
    "村": "Ngôi làng",
    "卒業します": "Tốt nghiệp",
    "映画館": "Rạp chiếu phim",
    "嫌［な］": "Khó chịu, ghét, không thích",
    "空": "Bầu trời",
    "閉じます": "Đóng (mắt, sách)",
    "都会": "Đô thị, thành phố lớn",
    "子どもたち": "Trẻ em, con nít",
    "自由に": "Tự do, thoải mái",
    "始まります［式が～］": "Bắt đầu [buổi lễ bắt đầu]",
    "入学します［大学に～］": "Nhập học [vào đại học]",
    "出席します［会議に～］": "Tham dự [cuộc họp]",
    "お客［さん］": "Khách hàng, quý khách",
    "誰か": "Ai đó, một ai đó",
    "普通の": "Bình thường, thông thường",
    "世界中": "Trên toàn thế giới",
    "集まります": "Tập hợp, tụ tập",
    "美しい": "Đẹp đẽ, tuyệt đẹp",
    "自然": "Tự nhiên, thiên nhiên",
    "すばらしさ": "Vẻ đẹp tuyệt vời, sự tuyệt vời",
    "気が つきます": "Nhận ra, để ý thấy",

    # --- BÀI 32 ---
    "運動します": "Vận động, tập thể dục",
    "成功します": "Thành công",
    "失敗します［試験に～］": "Thất bại, trượt [kỳ thi]",
    "合格します［試験に～］": "Thi đỗ, vượt qua [kỳ thi]",
    "やみます［雨が～］": "Tạnh, ngừng [mưa tạnh]",
    "晴れます": "Nắng, trời quang mây",
    "曇ります": "Nhiều mây, trời âm u",
    "続きます［熱が～］": "Kéo dài, tiếp diễn [cơn sốt kéo dài]",
    "ひきます［かぜを～］": "Mắc, nhiễm [cảm cúm]",
    "冷やします": "Làm lạnh, chườm lạnh",
    "出ます［試合に～］": "Tham gia [trận đấu]",
    "出ます［パーティーに～］": "Dự [bữa tiệc]",
    "無理を します": "Làm quá sức, làm cố",
    "十分［な］": "Đầy đủ",
    "おかしい": "Kỳ quặc, lạ lùng, buồn cười",
    "うるさい": "Ồn ào, phiền phức",
    "やけど": "Bị bỏng (やけどをします: bị bỏng)",
    "けが": "Vết thương (けがをします: bị thương)",
    "せき": "Cơn ho (せきが出ます: bị ho)",
    "インフルエンザ": "Bệnh cúm dịch",
    "太陽": "Mặt trời",
    "星": "Ngôi sao",
    "風": "Gió",
    "東": "Phía Đông",
    "西": "Phía Tây",
    "南": "Phía Nam",
    "北": "Phía Bắc",
    "国際～": "Quốc tế ~",
    "水道": "Nước máy",
    "エンジン": "Động cơ máy",
    "チーム": "Đội, nhóm (Team)",
    "今夜": "Tối nay, đêm nay",
    "夕方": "Chiều tối, hoàng hôn",
    "まえ": "Trước đây, hồi trước",
    "遅く": "Muộn, khuya",
    "こんなに": "Như thế này",
    "そんなに": "Đến mức như thế đó",
    "あんなに": "Đến mức như thế kia",
    "元気": "Khỏe khoắn, sinh khí",
    "胃": "Dạ dày, bao tử",
    "ストレス": "Căng thẳng, áp lực (Stress)",
    "それは いけませんね。": "Thế thì không được rồi / Thật đáng tiếc nhỉ.",
    "星占い": "Bói sao, tử vi chiêm tinh",
    "牡牛座": "Chòm sao Kim Ngưu",
    "働きすぎ": "Làm việc quá sức",
    "宝くじ": "Vé số, vé xổ số",
    "当たります［宝くじが～］": "Trúng [vé số]",
    "健康": "Sức khỏe",
    "恋愛": "Tình yêu",
    "恋人": "Người yêu",
    "ラッキーアイテム": "Đồ vật may mắn",
    "石": "Hòn đá",
    "戻ります": "Quay trở lại",
    "吹きます［風が～］": "Thổi [gió thổi]",
    "治ります［病気が～］": "Khỏi [bệnh]",
    "直ります［故障が～］": "Được sửa xong [chỗ hỏng]",
    "もしかしたら": "Biết đâu chừng, có thể là",
    "ゆっくり します": "Nghỉ ngơi thong thả",
    "［お］金持ち": "Người giàu có",

    # --- BÀI 33 ---
    "逃げます": "Chạy trốn, tẩu thoát",
    "騒ぎます": "Làm ồn, làm huyên náo",
    "あきらめます": "Từ bỏ, bỏ cuộc",
    "投げます": "Ném",
    "守ります": "Tuân thủ, giữ gìn, bảo vệ",
    "伝えます": "Truyền đạt lại, nhắn lại",
    "注意します［車に～］": "Chú ý, cẩn thận [xe cộ]",
    "外します［席を～］": "Rời [chỗ ngồi], vắng mặt",
    "あります［電話が～］": "Có [cuộc điện thoại gọi đến]",
    "リサイクルします": "Tái chế",
    "だめ［な］": "Không được, hỏng, vô ích",
    "警察": "Cảnh sát, đồn cảnh sát",
    "席": "Chỗ ngồi, ghế",
    "マーク": "Ký hiệu, dấu hiệu (Mark)",
    "ボール": "Quả bóng",
    "締め切り": "Hạn chót, hạn nộp",
    "規則": "Quy tắc, nội quy",
    "危険": "Nguy hiểm (biển báo)",
    "使用禁止": "Cấm sử dụng",
    "立入禁止": "Cấm vào",
    "徐行": "Đi chậm, giảm tốc độ",
    "入口": "Lối vào, cửa vào",
    "出口": "Lối ra, cửa ra",
    "非常口": "Cửa thoát hiểm",
    "無料": "Miễn phí",
    "割引": "Giảm giá",
    "飲み放題": "Uống thỏa thích, uống thả ga",
    "使用中": "Đang sử dụng",
    "募集中": "Đang tuyển dụng",
    "～中": "Đang trong lúc ~",
    "どういう ～": "~ như thế nào",
    "駐車違反": "Vi phạm đỗ xe trái phép",
    "罰金": "Tiền phạt",
    "助け合います": "Giúp đỡ lẫn nhau",
    "もともと": "Vốn dĩ, ban đầu",
    "悲しい": "Buồn bã, đau buồn",
    "もっと": "Hơn nữa, thêm nữa",
    "あいさつ": "Chào hỏi",
    "相手": "Đối phương, người đối diện",
    "気持ち": "Tâm trạng, cảm xúc",
    "上げます": "Nâng lên, giơ lên",
    "下げます": "Hạ xuống, kéo xuống",
    "ファイト": "Cố lên! Quyết chiến!",
    "洗濯機": "Máy giặt",
    "本日休業": "Hôm nay đóng cửa nghỉ",
    "営業中": "Đang mở cửa kinh doanh",
    "～以内": "Trong vòng ~",
    "電報": "Bức điện tín",
    "人々": "Mọi người, con người",
    "急用": "Việc khẩn cấp, việc gấp",
    "打ちます［電報を～］": "Đánh [điện tín]",
    "電報代": "Cước phí điện tín",
    "できるだけ": "Hết sức có thể, cố gắng tối đa",
    "短く": "Ngắn gọn",
    "危篤": "Nguy kịch, hấp hối",
    "重い 病気": "Bệnh nặng",
    "明日": "Ngày mai",
    "留守": "Vắng nhà",
    "留守番": "Trông nhà (khi chủ vắng)",
    "［お］祝い": "Chúc mừng, quà mừng",
    "亡くなります": "Qua đời (nói giảm của しにます)",
    "悲しみ": "Nỗi đau buồn",
    "利用します": "Sử dụng, tận dụng",

    # --- BÀI 34 ---
    "磨きます［歯を～］": "Đánh [răng], mài, đánh bóng",
    "組み立てます": "Lắp ráp",
    "折ります": "Bẻ, gập lại",
    "気が つきます［忘れ物に～］": "Nhận ra, để ý thấy [đồ để quên]",
    "つけます［しょうゆを～］": "Chấm [nước tương]",
    "見つかります［かぎが～］": "Được tìm thấy [chìa khóa được tìm thấy]",
    "質問します": "Hỏi, đặt câu hỏi",
    "さします［傘を～］": "Che [ô, dù]",
    "スポーツクラブ": "Câu lạc bộ thể thao",
    "［お］城": "Lâu đài, thành quách",
    "説明書": "Sách hướng dẫn sử dụng",
    "図": "Sơ đồ, hình vẽ minh họa",
    "線": "Đường kẻ, vạch kẻ",
    "矢印": "Dấu mũi tên",
    "黒": "Màu đen",
    "白": "Màu trắng",
    "赤": "Màu đỏ",
    "青": "Màu xanh lam",
    "紺": "Màu xanh lam đậm",
    "黄色": "Màu vàng",
    "茶色": "Màu nâu",
    "しょうゆ": "Nước tương (xì dầu)",
    "ソース": "Nước xốt Sauce",
    "～か ～": "~ hoặc là ~",
    "ゆうべ": "Tối qua, đêm qua",
    "さっき": "Vừa rồi, ban nãy",
    "茶道": "Trà đạo",
    "お茶を たてます": "Đánh trà, pha trà (Trà đạo)",
    "先に": "Trước (thời gian, thứ tự)",
    "載せます": "Đặt lên, xếp lên",
    "これで いいですか。": "Thế này đã được chưa ạ?",
    "苦い": "Đắng",
    "親子どんぶり": "Món cơm gà trứng Oyakodon",
    "材料": "Nguyên liệu, vật liệu",
    "～分": "Phần cho ~ người (khẩu phần)",
    "－グラム": "Gram (g)",
    "ー個": "Cái, quả (đếm vật nhỏ)",
    "たまねぎ": "Củ hành tây",
    "４分の１（１／４）": "Một phần tư (1/4)",
    "調味料": "Gia vị",
    "適当な 大きさに": "Cắt cỡ vừa ăn / Kích thước phù hợp",
    "なべ": "Cái xoong, nồi",
    "火": "Lửa, bếp lửa",
    "火に かけます": "Bắc lên bếp nấu",
    "煮ます": "Ninh, nấu, hầm",
    "煮えます": "Chín, được ninh nhừ",
    "どんぶり": "Tô to, bát sứ đựng cơm",
    "たちます": "Trôi qua (thời gian)",
    "細い": "Mảnh mai, thon nhỏ",
    "太い": "To, béo, dày",
    "キー": "Chìa khóa (Key)",
    "シートベルト": "Dây an toàn (xe cộ)",
    "鳥肉": "Thịt gà",

    # --- BÀI 35 ---
    "咲きます［花が～］": "Nở [hoa nở]",
    "変わります［色が～］": "Đổi, biến đổi [màu sắc]",
    "困ります": "Gặp khó khăn, rắc rối",
    "付けます［丸を～］": "Khoanh tròn, đánh dấu [vòng tròn]",
    "治ります［病気が～］": "Khỏi [bệnh]",
    "直ります［故障が～］": "Được sửa xong [chỗ hỏng]",
    "クリックします": "Nhấp chuột, click",
    "入力します": "Nhập dữ liệu (vào máy)",
    "正しい": "Đúng, chính xác",
    "向こう": "Phía bên kia, đằng kia",
    "島": "Hòn đảo",
    "港": "Bến cảng",
    "近所": "Khu vực lân cận, hàng xóm",
    "屋上": "Sân thượng, nóc nhà",
    "海外": "Nước ngoài, hải ngoại",
    "山登り": "Leo núi",
    "歴史": "Lịch sử",
    "機会": "Cơ hội, dịp",
    "許可": "Sự cho phép, cấp phép",
    "丸": "Vòng tròn, hình tròn",
    "ふりがな": "Chữ Furigana (chữ phiên âm cách đọc)",
    "設備": "Thiết bị, cơ sở vật chất",
    "レバー": "Cần gạt, tay cầm",
    "カーテン": "Rèm cửa",
    "ひも": "Sợi dây",
    "炊飯器": "Nồi cơm điện",
    "葉": "Lá cây",
    "これで 終わりましょう。": "Chúng ta hãy kết thúc tại đây nhé.",
    "それなら": "Nếu thế thì, trong trường hợp đó",
    "夜行バス": "Xe buýt chạy đêm",
    "旅行社": "Công ty du lịch",
    "詳しい": "Tường tận, rành rẽ, chi tiết",
    "スキー場": "Khu trượt tuyết",
    "ことわざ": "Tục ngữ",
    "関係": "Mối quan hệ, can hệ",
    "仲よく します": "Chơi thân với nhau, hòa thuận",
    "必要［な］": "Cần thiết",
    "楽［な］": "Dễ chịu, thoải mái, nhàn hạ",
    "珍しい": "Hiếm có, quý hiếm",
    "ハイキング": "Đi bộ dã ngoại, leo núi ngắm cảnh",
    "操作": "Thao tác, vận hành",
    "方法": "Phương pháp, cách thức",
    "ふた": "Cái nắp, vung",
    "曲": "Bản nhạc, khúc nhạc",
    "楽しみ": "Niềm vui, sự mong đợi",
    "初めに": "Trước hết, đầu tiên",
    "これで 終わります。": "Đến đây là kết thúc.",

    # --- BÀI 36 ---
    "あいます［事故に～］": "Gặp phải [tai nạn]",
    "貯金します": "Tiết kiệm tiền",
    "過ぎます［７時を～］": "Quá [7 giờ]",
    "慣れます［仕事に～］": "Quen với [công việc]",
    "腐ります［食べ物が～］": "Ôi thiu, thối rữa [thức ăn]",
    "剣道": "Kiếm đạo Kendo",
    "毎週": "Hàng tuần",
    "毎月": "Hàng tháng",
    "毎年": "Hàng năm",
    "このごろ": "Dạo này, thời gian gần đây",
    "やっと": "Cuối cùng thì (sau cố gắng)",
    "かなり": "Khá là, tương đối",
    "必ず": "Chắc chắn, nhất định",
    "絶対に": "Tuyệt đối (đi với phủ định)",
    "上手に": "Giỏi giang, khéo léo",
    "お客様": "Quý khách (kính cẩn của お客さん)",
    "特別［な］": "Đặc biệt",
    "して いらっしゃいます": "Đang làm (Kính ngữ của しています)",
    "水泳": "Môn bơi lội",
    "チャレンジします": "Thử sức, thử thách",
    "乗り物": "Phương tiện đi lại",
    "ー世紀": "Thế kỷ thứ -",
    "遠く": "Nơi xa xôi, đằng xa",
    "汽車": "Tàu hỏa chạy bằng hơi nước",
    "汽船": "Tàu thủy chạy bằng hơi nước",
    "大勢の ～": "Đông đảo ~ (người)",
    "運びます": "Chuyên chở, vận chuyển",
    "届きます［荷物が～］": "Được gửi đến [hàng hóa]",
    "太ります": "Béo lên, tăng cân",
    "やせます": "Gầy đi, giảm cân",
    "硬い": "Cứng rắn",
    "軟らかい": "Mềm mại",
    "電子～": "Điện tử ~",
    "携帯～": "Cầm tay, di động ~",
    "工場": "Nhà máy, công xưởng",
    "～ずつ": "Từng ~ một (số lượng)",
    "その ほうが ～": "Cách đó thì ~ hơn",
    "タンゴ": "Điệu nhảy Tango",
    "安全［な］": "An toàn",

    # --- BÀI 37 ---
    "褒めます": "Khen ngợi, tán dương",
    "しかります": "Mắng, la mắng",
    "誘います": "Rủ rê, mời",
    "招待します": "Mời, chiêu đãi",
    "頼みます": "Nhờ vả, yêu cầu",
    "注意します": "Nhắc nhở, lưu ý",
    "とります": "Lấy trộm, ăn cắp",
    "踏みます": "Giẫm lên, đạp vào",
    "壊します": "Làm hỏng, phá hủy",
    "汚します": "Làm bẩn",
    "行います": "Tổ chức, tiến hành",
    "輸出します": "Xuất khẩu",
    "輸入します": "Nhập khẩu",
    "翻訳します": "Biên dịch",
    "発明します": "Phát minh",
    "発見します": "Phát hiện, tìm ra",
    "米": "Gạo",
    "麦": "Lúa mạch, lúa mì",
    "石油": "Dầu mỏ, dầu hỏa",
    "原料": "Nguyên liệu chế biến",
    "インスタントラーメン": "Mì ăn liền",
    "デート": "Buổi hẹn hò (nam nữ)",
    "泥棒": "Kẻ trộm, tên trộm",
    "警官": "Viên cảnh sát",
    "何語": "Tiếng gì, ngôn ngữ gì",
    "よかったですね。": "Tốt quá rồi nhỉ / May quá nhỉ.",
    "皆様": "Quý vị, mọi người (kính ngữ)",
    "焼けます［うちが～］": "Cháy [ngôi nhà bị cháy]",
    "その 後": "Sau đó",
    "世界遺産": "Di sản thế giới",
    "～の 一つ": "Một trong những ~",
    "金色": "Màu vàng óng, mạ vàng",
    "本物": "Hàng thật, đồ thật",
    "金": "Vàng (kim loại quý)",
    "－キロ": "Kilôgam / Kilômét",
    "豪華［な］": "Xa hoa, lộng lẫy, sang trọng",
    "彫刻": "Tác phẩm điêu khắc",
    "言い伝え": "Truyền thuyết lưu truyền",
    "眠ります": "Ngủ",
    "彫ります": "Điêu khắc, chạm trổ",
    "仲間": "Bạn bè, đồng nghiệp cùng hội",
    "一生懸命": "Cố gắng hết sức mình, chăm chỉ",
    "ねずみ": "Con chuột",
    "一匹も いません。": "Không có lấy một con nào.",
    "眠り猫": "Mèo ngủ (bức điêu khắc ở Nikko)",
    "起こします": "Đánh thức (ai đó) dậy",
    "設計します": "Thiết kế",
    "建築家": "Kiến trúc sư",
    "科学者": "Nhà khoa học",
    "漫画": "Truyện tranh Manga",
    "～に よって": "Do ~, bởi ~ sáng tạo ra",
    "埋め立てます": "San lấp đất, lấp biển",
    "技術": "Kỹ thuật, công nghệ",
    "土地": "Mảnh đất, đất đai",
    "騒音": "Tiếng ồn",
    "アクセス": "Giao thông kết nối, đường tới",

    # --- BÀI 38 ---
    "参加します［旅行に～］": "Tham gia [chuyến du lịch]",
    "育てます": "Nuôi dạy (con), trồng (cây)",
    "入院します": "Nhập viện, vào viện",
    "退院します": "Xuất viện, ra viện",
    "入れます［電源を～］": "Bật [công tắc nguồn]",
    "切ります［電源を～］": "Tắt [công tắc nguồn]",
    "掛けます［かぎを～］": "Khóa [ổ khóa]",
    "つきます［うそを～］": "Nói [nói dối]",
    "気持ちが いい": "Tâm trạng thoải mái, sảng khoái",
    "気持ちが 悪い": "Tâm trạng khó chịu, kinh tởm",
    "大きな ～": "~ to lớn",
    "小さな ～": "~ nhỏ bé",
    "赤ちゃん": "Em bé sơ sinh",
    "小学校": "Trường tiểu học",
    "中学校": "Trường trung học cơ sở (cấp 2)",
    "海岸": "Bờ biển",
    "かな": "Chữ Kana (Hiragana & Katakana)",
    "指輪": "Chiếc nhẫn",
    "電源": "Nguồn điện, công tắc nguồn",
    "～製": "Sản xuất tại ~",
    "おととし": "Năm kia",
    "［あ、］いけない。": "Ôi hỏng rồi! Chết rồi! (khi nhầm lẫn)",
    "お先に［失礼します］。": "Tôi xin phép về trước ạ.",
    "回覧": "Tập thông báo luân chuyển trong xóm",
    "研究室": "Phòng nghiên cứu của giáo sư",
    "きちんと": "Ngăn nắp, chỉn chu, gọn gàng",
    "整理します": "Sắp xếp, thu dọn phân loại",
    "～と いう": "Có tên gọi là ~",
    "－冊": "Cuốn, quyển (đếm sách, vở)",
    "はんこ": "Con dấu cá nhân",
    "押します［はんこを～］": "Đóng [dấu]",
    "双子": "Cặp sinh đôi",
    "姉妹": "Chị em gái",
    "５年生": "Học sinh lớp 5",
    "似て います": "Giống nhau",
    "性格": "Tính cách",
    "おとなしい": "Ngoan ngoãn, hiền lành, trầm tính",
    "優しい": "Hiền lành, dịu dàng, tốt bụng",
    "世話を します": "Chăm sóc, chăm nom",
    "時間が たちます": "Thời gian trôi qua",
    "－点": "Điểm (thang điểm)",
    "気が 強い": "Cá tính cứng cỏi, hiếu thắng",
    "けんかします": "Cãi nhau, đánh nhau",
    "不思議［な］": "Kỳ lạ, huyền bí",
    "年齢": "Tuổi tác",
    "しかた": "Cách làm, phương pháp",
    "書類": "Giấy tờ, tài liệu",

    # --- BÀI 39 ---
    "答えます［質問に～］": "Trả lời [câu hỏi]",
    "倒れます［ビルが～］": "Đổ sập [tòa nhà sụp đổ]",
    "通ります［道を～］": "Đi qua, chạy qua [con đường]",
    "死にます": "Chết, qua đời",
    "びっくりします": "Giật mình, kinh ngạc",
    "がっかりします": "Thất vọng, chán chường",
    "安心します": "An tâm, yên tâm",
    "離婚します": "Ly hôn, ly dị",
    "複雑［な］": "Phức tạp, rắc rối",
    "邪魔［な］": "Cản trở, vướng víu, làm phiền",
    "汚い": "Bẩn thỉu, dơ bẩn",
    "恥ずかしい": "Xấu hổ, ngượng ngùng",
    "津波": "Sóng thần Tsunami",
    "台風": "Cơn bão lớn, bão nhiệt đới",
    "雷": "Sấm sét",
    "火事": "Hỏa hoạn, vụ cháy",
    "事後": "Tai nạn giao thông",
    "［お］見合い": "Buổi xem mắt để kết hôn (Omiai)",
    "会場": "Hội trường, địa điểm tổ chức",
    "～代": "Tiền cước, phí dịch vụ ~",
    "フロント": "Quầy lễ tân (khách sạn)",
    "－号室": "Phòng số -",
    "タオル": "Khăn tắm, khăn mặt",
    "せっけん": "Bánh xà phòng",
    "大勢": "Đông người, đám đông",
    "お疲れ様でした。": "Anh/chị đã vất vả rồi (chào sau buổi làm việc).",
    "伺います。": "Tôi xin phép đến thăm (Khiêm nhường ngữ).",
    "途中で": "Nửa chừng, giữa đường",
    "トラック": "Xe tải",
    "ぶつかります": "Đâm vào, va chạm",
    "大人": "Người lớn, người trưởng thành",
    "洋服": "Quần áo kiểu Âu, âu phục",
    "西洋化します": "Tây phương hóa, Âu hóa",
    "合います": "Vừa vặn, hợp với",
    "今では": "Hiện nay, bây giờ",
    "成人式": "Lễ trưởng thành (20 tuổi ở Nhật)",
    "伝統的［な］": "Mang tính truyền thống",
    "焼けます［パンが～］": "Nướng chín [bánh mì]",
    "焼けます［肉が～］": "Nướng chín [thịt]",
    "遅刻します": "Đi muộn, trễ giờ",
    "早退します": "Về sớm (trước giờ tan làm/học)",
    "電話代": "Cước phí điện thoại",
    "汗": "Mồ hôi (汗をかきます: toát mồ hôi)",
    "並びます": "Xếp hàng",

    # --- BÀI 40 ---
    "数えます": "Đếm",
    "測ります、量ります": "Đo, cân, đong",
    "確かめます": "Xác nhận, kiểm tra lại",
    "合います［サイズが～］": "Vừa vặn [kích cỡ vừa]",
    "出発します": "Xuất phát, khởi hành",
    "到着します": "Đến nơi, cập bến",
    "酔います": "Say (rượu, tàu xe)",
    "うまく いきます": "Diễn ra trôi chảy, thuận lợi",
    "出ます［問題が～］": "Ra đề, xuất hiện [câu hỏi thi]",
    "忘年会": "Tiệc tất niên",
    "新年会": "Tiệc tân niên",
    "二次会": "Tăng hai (bữa liên hoan tiếp theo)",
    "発表会": "Buổi báo cáo, thuyết trình",
    "大会": "Đại hội, cuộc thi lớn",
    "マラソン": "Cuộc chạy Marathon",
    "コンテスト": "Cuộc thi tài (Contest)",
    "表": "Mặt trước, mặt phải",
    "裏": "Mặt sau, mặt trái",
    "まちがい": "Sai sót, lỗi lầm",
    "傷": "Vết xước, vết thương, tì vết",
    "ズボン": "Quần dài",
    "［お］年寄り": "Người cao tuổi, người già",
    "長さ": "Chiều dài",
    "重さ": "Cân nặng, trọng lượng",
    "高さ": "Chiều cao, độ cao",
    "大きさ": "Kích cỡ, độ lớn",
    "［－］便": "Chuyến bay số [－]",
    "－個": "Cái, quả, chiếc (đếm vật nhỏ tròn)",
    "－本": "Cây, chiếc, chai (đếm vật thon dài)",
    "－杯": "Cốc, chén (đếm đồ uống đầy cốc)",
    "－センチ": "Centimet (cm)",
    "－ミリ": "Milimet (mm)",
    "－グラム": "Gram (g)",
    "～以上": "Từ ~ trở lên",
    "～以下": "Từ ~ trở xuống",
    "どうでしょうか。": "Như thế nào rồi ạ? (lịch sự của どうですか)",
    "テスト": "Bài kiểm tra (Test)",
    "成績": "Thành tích, kết quả học tập",
    "ところで": "Nhân tiện, tiện đây (chuyển chủ đề)",
    "様子": "Tình hình, dáng vẻ",
    "事件": "Vụ án, vụ việc",
    "オートバイ": "Xe máy, xe mô tô",
    "爆弾": "Quả bom",
    "積みます": "Chất lên, xếp lên (xe)",
    "運転手": "Tài xế, người lái xe",
    "離れた": "Cách xa, xa xôi",
    "急に": "Đột ngột, bất thình lình",
    "動かします": "Khởi động, vận hành, làm chuyển động",
    "犯人": "Thủ phạm, tội phạm",
    "男": "Người đàn ông",
    "手に 入れます": "Đoạt được, có được trong tay",
    "今でも": "Ngay cả bây giờ"
}

def clean_meaning_str(text):
    if not text:
        return ""
    import re
    t = re.sub(r"#.*$", "", text).strip()
    t = t.strip("\"'“””")
    t = t.rstrip(",").strip()
    return t

def apply_part4():
    file_path = "src/data/minna_lessons.json"
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    updated = 0
    for lesson in data:
        if 31 <= lesson.get("lesson") <= 40:
            for w in lesson.get("words", []):
                k = (w.get("kanji") or "").strip()
                kn = (w.get("kana") or "").strip()
                clean_en = clean_meaning_str(w.get("meaning_en", ""))
                w["meaning_en"] = clean_en
                # Match
                for dict_key, correct_m in MINNA_LESSONS_31_40.items():
                    if k == dict_key or kn == dict_key or k.replace(" ", "") == dict_key.replace(" ", ""):
                        w["meaning"] = correct_m
                        updated += 1
                        break

    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"-> Hoàn tất chuẩn hóa Bài 31 - 40: Cập nhật {updated} từ!")

if __name__ == "__main__":
    apply_part4()
