# -*- coding: utf-8 -*-
"""
Minna no Nihongo - Chuẩn hóa Bài 21 đến Bài 30 theo Sách Giáo Trình tiếng Việt chính thức.
"""
import json
import sys

sys.stdout.reconfigure(encoding='utf-8')

MINNA_LESSONS_21_30 = {
    # --- BÀI 21 ---
    "思います": "Nghĩ, suy nghĩ",
    "言います": "Nói",
    "勝ちます": "Thắng, chiến thắng",
    "負けます": "Thua, thất bại",
    "あります［お祭りが～］": "Có, được tổ chức [lễ hội ~]",
    "役に 立ちます": "Có ích, hữu ích",
    "動きます": "Chuyển động, hoạt động (máy móc)",
    "やめます［会社を～］": "Nghỉ việc, bỏ [công ty]",
    "気を つけます": "Chú ý, cẩn thận",
    "留学します": "Đi du học",
    "むだ［な］": "Lãng phí, vô ích",
    "不便［な］": "Bất tiện",
    "すごい": "Kinh khủng, tuyệt vời, giỏi quá",
    "ほんとう": "Sự thật",
    "うそ": "Lời nói dối, chuyện bịa",
    "自動車": "Xe ô tô",
    "交通": "Giao thông",
    "物価": "Vật giá, giá cả",
    "放送": "Phát thanh, truyền hình",
    "ニュース": "Tin tức, thời sự",
    "アニメ": "Phim hoạt hình Anime",
    "マンガ": "Truyện tranh Manga",
    "デザイン": "Thiết kế",
    "夢": "Giấc mơ, ước mơ",
    "天才": "Thiên tài",
    "試合": "Trận đấu, cuộc thi đấu",
    "意見": "Ý kiến",
    "話": "Câu chuyện, bài nói chuyện",
    "地球": "Trái Đất",
    "月": "Mặt trăng",
    "最近": "Dạo gần đây, gần đây",
    "たぶん": "Có lẽ, chắc là",
    "きっと": "Chắc chắn, nhất định",
    "ほんとうに": "Thật sự, quả thật",
    "そんなに": "Không đến mức như thế (đi với phủ định)",
    "～に ついて": "Về việc ~, liên quan đến ~",
    "久しぶりですね。": "Lâu lắm rồi mới gặp lại nhỉ!",
    "～でも 飲みませんか。": "Uống ~ hay thứ gì đó nhé?",
    "もちろん": "Tất nhiên, đương nhiên",
    "もう 帰らないと……。": "Tôi phải về rồi...",
    "足ります": "Đủ, đầy đủ",
    "同じ": "Giống nhau, như nhau",
    "首相": "Thủ tướng",
    "大統領": "Tổng thống",
    "政治": "Chính trị",
    "スピーチ": "Bài phát biểu, diễn thuyết",
    "ユーモア": "Sự hài hước, óc hài hước",
    "むだ": "Sự lãng phí, vô ích",
    "ラッシュ": "Giờ cao điểm",
    "しかたが ありません。": "Không còn cách nào khác / Đành chịu thôi.",
    "しばらくですね。": "Lâu ngày không gặp nhỉ.",
    "見ないと……。": "Tôi phải xem mới được...",

    # --- BÀI 22 ---
    "着ます": "Mặc (áo sơ mi, áo khoác...)",
    "はきます": "Đi, xỏ (giày), mặc (quần, váy)",
    "かぶります": "Đội (mũ, nón)",
    "かけます［眼鏡を～］": "Đeo [kính]",
    "します［ネクタイを～］": "Đeo, thắt [cà vạt]",
    "生まれます": "Sinh ra, chào đời",
    "コート": "Áo khoác, áo choàng",
    "セーター": "Áo len",
    "スーツ": "Bộ comple, vest",
    "帽子": "Mũ, nón",
    "眼鏡": "Kính mắt",
    "［お］弁当": "Cơm hộp Bento",
    "ロボット": "Người máy, robot",
    "都合": "Sự thuận tiện (về thời gian, điều kiện)",
    "よく": "Thường xuyên, rõ ràng",
    "おめでとう［ございます］。": "Xin chúc mừng!",
    "お探しですか。": "Bác/Anh/Chị đang tìm ~ đấy à?",
    "では": "Thế thì, vậy thì",
    "家賃": "Tiền thuê nhà",
    "ダイニングキッチン": "Bếp kèm phòng ăn",
    "和室": "Phòng kiểu Nhật (trải chiếu Tatami)",
    "押し入れ": "Tủ âm tường (đựng chăn đệm kiểu Nhật)",
    "布団": "Chăn đệm kiểu Nhật",
    "アパート": "Căn hộ chung cư nhỏ",
    "万裏の 長城": "Vạn Lý Trường Thành",

    # --- BÀI 23 ---
    "聞きます［先生に～］": "Hỏi [thầy cô giáo]",
    "回します": "Vặn, xoay",
    "引きます": "Kéo",
    "変えます": "Đổi, thay đổi",
    "触ります［ドアに～］": "Chạm vào, sờ vào [cửa]",
    "出ます［お釣りが～］": "Chảy ra, chạy ra [tiền thừa ra]",
    "歩きます": "Đi bộ",
    "渡ります［橋を～］": "Qua, đi qua [cây cầu]",
    "曲がります［右へ～］": "Rẽ, quẹo [về bên phải]",
    "［お］湯": "Nước nóng, nước sôi",
    "音": "Âm thanh, tiếng động",
    "サイズ": "Kích cỡ, size",
    "故障": "Sự cố, hỏng hóc",
    "道": "Con đường",
    "交差点": "Ngã tư, giao lộ",
    "信号": "Đèn giao thông",
    "角": "Góc phố, góc đường",
    "橋": "Cây cầu",
    "駐車場": "Bãi đỗ xe",
    "建物": "Tòa nhà, công trình kiến trúc",
    "－目": "Thứ - (số thứ tự, vd: 2つ目: cái thứ 2)",
    "動きます［時計が～］": "Chạy, hoạt động [đồng hồ chạy]",
    "気を つけます［車に～］": "Chú ý, cẩn thận [xe cộ]",
    "引っ越しします": "Chuyển nhà",
    "電気屋": "Cửa hàng đồ điện",
    "機械": "Máy móc",
    "つまみ": "Núm vặn, núm xoay",

    # --- BÀI 24 ---
    "くれます": "Cho, tặng (tôi hoặc người phe tôi)",
    "直します": "Sửa chữa, chỉnh sửa",
    "連れて 行きます": "Dẫn đi (người, động vật)",
    "連れて 来ます": "Dẫn đến",
    "送ります［人を～］": "Tiễn, đưa tiễn [ai đó]",
    "紹介します": "Giới thiệu",
    "案内します": "Hướng dẫn, chỉ đường",
    "説明します": "Giải thích",
    "おじいさん": "Ông, cụ ông (người khác)",
    "おじいちゃん": "Ông (gọi thân mật trong nhà)",
    "おばあさん": "Bà, cụ bà (người khác)",
    "おばあちゃん": "Bà (gọi thân mật trong nhà)",
    "準備": "Chuẩn bị",
    "引っ越し": "Chuyển nhà",
    "［お］菓子": "Bánh kẹo",
    "ホームステイ": "Ở cùng gia đình bản xứ (Homestay)",
    "全部": "Toàn bộ, tất cả",
    "自分で": "Tự mình",
    "ほかに": "Ngoài ra, bên cạnh đó",
    "母の 日": "Ngày của Mẹ",
    "いれます［コーヒーを～］": "Pha [cà phê]",
    "意味": "Ý nghĩa",
    "ワゴン車": "Xe chở hàng nhẹ, xe thùng",

    # --- BÀI 25 ---
    "考えます": "Suy nghĩ, nghĩ",
    "着きます": "Đến nơi, tới ga",
    "取ります［年を～］": "Thêm tuổi, già đi",
    "田舎": "Quê hương, vùng nông thôn",
    "チャンス": "Cơ hội",
    "億": "Một trăm triệu (ức)",
    "もし［～たら］": "Nếu [~ thì]",
    "転勤": "Chuyển công tác (chi nhánh khác)",
    "こと": "Việc, điều, chuyện",
    "暇": "Thời gian rảnh rỗi",
    "［いろいろ］お世話に なりました。": "Cảm ơn anh/chị đã giúp đỡ tôi rất nhiều.",
    "頑張ります": "Cố gắng hết sức",
    "どうぞ お元気で。": "Chúc anh/chị luôn mạnh khỏe (khi chia tay lâu).",
    "大使館": "Đại sứ quán",
    "グループ": "Nhóm, đoàn",
    "いくら［～でも］": "Dù cho... bao nhiêu đi nữa [thì...]",
    "一杯 飲みましょう。": "Chúng ta cùng uống một ly nhé!",

    # --- BÀI 26 ---
    "見ます、診ます": "Xem xét, khám bệnh",
    "探します、捜します": "Tìm kiếm",
    "遅れます［時間に～］": "Chậm, muộn [giờ hẹn]",
    "間に 合います［時間に～］": "Kịp [giờ hẹn]",
    "やります": "Làm, chơi",
    "拾います": "Nhặt, lượm",
    "連絡します": "Liên lạc",
    "気分が いい": "Cảm thấy khỏe khoắn, sảng khoái",
    "気分が 悪い": "Cảm thấy khó chịu, mệt mỏi trong người",
    "運動会": "Ngày hội thể thao",
    "盆踊り": "Điệu múa Bon (trong lễ hội)",
    "フリーマーケット": "Chợ đồ cũ, chợ trời",
    "場所": "Địa điểm, nơi chốn",
    "ボランティア": "Tình nguyện viên",
    "財布": "Ví tiền, bóp tiền",
    "ごみ": "Rác",
    "国会議事堂": "Tòa nhà Quốc hội",
    "平日": "Ngày thường (thứ hai đến thứ sáu)",
    "～弁": "Giọng địa phương, tiếng địa phương ~",
    "今度": "Lần này, lần tới",
    "ずいぶん": "Khá là, tương đối nhiều",
    "直接": "Trực tiếp",
    "いつでも": "Bất cứ lúc nào",
    "どこでも": "Bất cứ nơi đâu",
    "だれでも": "Bất cứ ai",
    "何でも": "Cái gì cũng",
    "こんな ～": "~ như thế này",
    "そんな ～": "~ như thế đó",
    "あんな ～": "~ như thế kia",
    "片づきます［荷物が～］": "Được dọn dẹp ngăn nắp [đồ đạc ~]",
    "出します［ごみを～］": "Đổ [rác], vứt [rác]",
    "燃える ごみ": "Rác cháy được",
    "置き場": "Chỗ để, nơi để",
    "横": "Bên cạnh, chiều ngang",
    "瓶": "Chai, lọ thủy tinh",
    "缶": "Lon, đồ hộp",
    "ガス": "Khí ga",
    "～会社": "Công ty ~",
    "宇宙": "Vũ trụ",
    "～様": "Ngài, ông, bà (kính xưng lịch sự của ～さん)",
    "宇宙船": "Tàu vũ trụ",
    "怖い": "Sợ hãi, đáng sợ",
    "宇宙ステーション": "Trạm không gian, trạm vũ trụ",
    "宇宙飛行士": "Phi hành gia vũ trụ",
    "参加します［パーティーに～］": "Tham gia [bữa tiệc]",
    "申し込みます": "Đăng ký",
    "都合が いい": "Thuận tiện (về thời gian)",
    "都合が 悪い": "Kẹt, không thuận tiện (về thời gian)",
    "新聞社": "Tòa soạn báo",
    "柔道": "Võ Judo, Nhu đạo",
    "こどもの 日": "Ngày thiếu nhi",
    "燃えます［ごみが～］": "Cháy được [rác ~]",
    "月・水・金": "Thứ hai, thứ tư, thứ sáu",
    "困ったなあ。": "Làm sao bây giờ nhỉ / Gay go thật.",
    "電子メール": "Thư điện tử, email",
    "別の": "Khác, cái khác",

    # --- BÀI 27 ---
    "飼います": "Nuôi (thú cưng, động vật)",
    "走ります［道を～］": "Chạy [trên đường]",
    "見えます［山が～］": "Nhìn thấy, trông thấy [ngọn núi]",
    "聞こえます［音が～］": "Nghe thấy [âm thanh]",
    "できます［道が～］": "Được hoàn thành, làm xong [con đường]",
    "開きます［教室を～］": "Mở [lớp học]",
    "心配［な］": "Lo lắng",
    "ペット": "Thú cưng, vật nuôi",
    "鳥": "Con chim",
    "声": "Tiếng, giọng nói (người, động vật)",
    "波": "Sóng biển",
    "花火": "Pháo hoa",
    "道具": "Dụng cụ, công cụ",
    "クリーニング": "Giặt là, tiệm giặt ủi",
    "家": "Ngôi nhà",
    "マンション": "Chung cư cao cấp, căn hộ",
    "キッチン": "Nhà bếp",
    "～教室": "Lớp học ~",
    "パーティールーム": "Phòng tiệc",
    "方": "Vị, ngài (lịch sự của ひと)",
    "～後": "Sau ~ (khoảng thời gian)",
    "～しか": "Chỉ ~ (đi kèm với phủ định)",
    "ほかの": "Khác",
    "はっきり": "Rõ ràng",
    "家具": "Đồ gỗ nội thất, bàn ghế",
    "本棚": "Giá sách, kệ sách",
    "いつか": "Một ngày nào đó, lúc nào đó",
    "建てます": "Xây dựng",
    "すばらしい": "Tuyệt vời, tráng lệ",
    "子どもたち": "Trẻ con, các cháu bé",
    "大好き［な］": "Rất thích",
    "主人公": "Nhân vật chính",
    "形": "Hình dáng, kiểu dáng",
    "不思議［な］": "Kỳ lạ, huyền bí, kỳ diệu",
    "ポケット": "Túi áo, túi quần",
    "例えば": "Ví dụ như, chẳng hạn",
    "付けます": "Gắn vào, dán vào",
    "自由に": "Tự do, thoải mái",
    "空": "Bầu trời",
    "飛びます": "Bay",
    "昔": "Ngày xưa, thời xưa",
    "自分": "Tự mình, bản thân",
    "将来": "Tương lai",
    "景色": "Phong cảnh, cảnh sắc",
    "昼間": "Ban ngày",
    "通信販売": "Bán hàng qua mạng, đặt hàng qua thư",
    "台所": "Nhà bếp",
    "ほとんど": "Hầu như, hầu hết",

    # --- BÀI 28 ---
    "売れます［パンが～］": "Bán chạy [bánh mì]",
    "踊ります": "Nhảy múa, khiêu vũ",
    "かみます": "Nhai, cắn",
    "選びます": "Chọn, lựa chọn",
    "通います［大学に～］": "Đi học đều đặn [đại học], đi lại thường xuyên",
    "メモします": "Ghi chép lại, ghi chú",
    "まじめ［な］": "Nghiêm túc, chăm chỉ, đứng đắn",
    "熱心［な］": "Nhiệt tình, hăng hái",
    "偉い": "Vĩ đại, đáng ngưỡng mộ, giỏi giang",
    "ちょうど いい": "Vừa vặn, vừa đúng",
    "美容院": "Thẩm mỹ viện, tiệm làm tóc",
    "経験": "Kinh nghiệm",
    "力": "Sức lực, năng lực",
    "人気": "Sự yêu thích, hâm mộ",
    "色": "Màu sắc",
    "味": "Vị, mùi vị",
    "ガム": "Kẹo cao su",
    "品物": "Hàng hóa, mặt hàng",
    "値段": "Giá cả",
    "給料": "Tiền lương",
    "ボーナス": "Tiền thưởng",
    "ゲーム": "Trò chơi, game",
    "番組": "Chương trình (truyền hình, phát thanh)",
    "ドラマ": "Phim truyền hình drama",
    "歌手": "Ca sĩ",
    "小説": "Tiểu thuyết",
    "小説家": "Nhà văn, tiểu thuyết gia",
    "～家": "Nhà ~, chuyên gia ~ (vd: 小説家, 画家)",
    "～機": "Máy ~ (vd: コピー機)",
    "息子": "Con trai (của mình)",
    "息子さん": "Con trai (của người khác)",
    "娘": "Con gái (của mình)",
    "娘さん": "Con gái (của người khác)",
    "しばらく": "Một lúc, một lát, một thời gian",
    "たいてい": "Thường thường, hầu như",
    "それに": "Thêm vào đó, hơn nữa",
    "それで": "Vì thế, do đó mà",
    "［ちょっと］お願いが あるんですが。": "Tôi có chút việc muốn nhờ anh/chị...",
    "会話": "Hội thoại",
    "お知らせ": "Thông báo",
    "参加します": "Tham gia",
    "日にち": "Ngày tháng",
    "土": "Thứ Bảy (viết tắt của 土曜日)",
    "体育館": "Nhà thi đấu thể dục, nhà thể chất",
    "無料": "Miễn phí",
    "誘います": "Rủ rê, mời mọc",
    "イベント": "Sự kiện",
    "優しい": "Hiền lành, dịu dàng, tốt bụng",
    "習慣": "Thói quen, tập quán",
    "管理人": "Người quản lý, bác bảo vệ",
    "おしゃべりします": "Trò chuyện, tán gẫu",

    # --- BÀI 29 ---
    "開きます［ドアが～］": "Mở [cửa ~ mở]",
    "閉まります［ドアが～］": "Đóng [cửa ~ đóng]",
    "つきます［電気が～］": "Bật, sáng [đèn ~ sáng]",
    "消えます［電気が～］": "Tắt [đèn ~ tắt]",
    "壊れます［いすが～］": "Hỏng [ghế ~ hỏng]",
    "割れます［コップが～］": "Vỡ [cốc ~ vỡ]",
    "折れます［木が～］": "Gãy [cây ~ gãy]",
    "破れます［紙が～］": "Rách [giấy ~ rách]",
    "汚れます［服が～］": "Bẩn [quần áo ~ bẩn]",
    "付きます［ポケットが～］": "Có, dính, gắn kèm [túi áo ~]",
    "外れます［ボタンが～］": "Tuột, bung [cúc áo ~ bung]",
    "止まります［車が～］": "Dừng lại, đỗ [xe ~ dừng]",
    "まちがえます": "Nhầm lẫn, làm sai",
    "落とします": "Đánh rơi, làm rơi",
    "掛かります［かぎが～］": "Khóa [chìa khóa ~ khóa]",
    "ふきます": "Lau, chùi",
    "取り替えます": "Thay, đổi (cái mới)",
    "片づけます": "Dọn dẹp ngăn nắp",
    "［お］皿": "Cái đĩa",
    "［お］ちゃわん": "Cái bát (chén ăn cơm)",
    "コップ": "Cái cốc",
    "ガラス": "Thủy tinh, kính",
    "袋": "Túi, bao bì",
    "書類": "Tài liệu, giấy tờ",
    "枝": "Cành cây",
    "駅員": "Nhân viên nhà ga",
    "交番": "Đồn cảnh sát, bốt cảnh sát",
    "返事": "Câu trả lời, hồi âm",
    "お先に どうぞ。": "Xin mời anh/chị cứ đi trước ạ.",
    "源氏物語": "Truyện kể Genji (Genji Monogatari)",
    "今の 電車": "Chuyến tàu vừa rồi",
    "忘れ物": "Đồ bỏ quên, vật để quên",
    "このくらい": "Cỡ chừng này (độ lớn)",
    "～側": "Phía ~, bên ~",
    "～ 辺": "Khu vực quanh ~, vùng ~",
    "覚えて いません。": "Tôi không nhớ.",
    "網棚": "Giá để hành lý (trên tàu xe)",
    "確か": "Hình như là, chắc là",
    "［ああ、］よかった。": "Ôi, may quá rồi!",
    "地震": "Động đất",
    "壁": "Bức tường",
    "針": "Kim (đồng hồ)",
    "指します": "Chỉ vào, trỏ",
    "駅前": "Khu vực trước nhà ga",
    "倒れます": "Đổ, ngã (cây, tòa nhà)",
    "西": "Phía Tây",
    "～の 方": "Hướng của ~, phía ~",
    "燃えます": "Cháy",
    "レポーター": "Phóng viên truyền hình",
    "込みます［道が～］": "Đông đúc, tắc nghẽn [đường ~]",
    "すきます［道が～］": "Vắng vẻ, thông thoáng [đường ~]",
    "この 辺": "Khu vực quanh đây",

    # --- BÀI 30 ---
    "はります": "Dán, dán lên",
    "掛けます": "Treo (áo, tranh lên tường)",
    "飾ります": "Trang trí",
    "並べます": "Sắp xếp, xếp thành hàng",
    "植えます": "Trồng (cây)",
    "戻します": "Để lại, trả lại chỗ cũ",
    "まとめます": "Thu thập, tổng hợp, tóm tắt",
    "しまいます": "Cất vào, cất đi",
    "決めます": "Quyết định",
    "予習します": "Soạn bài, chuẩn bị bài trước",
    "復習します": "Ôn tập lại bài cũ",
    "そのままに します": "Để nguyên như thế",
    "授業": "Tiết học, giờ học",
    "講義": "Bài giảng",
    "ミーティング": "Cuộc họp (Meeting)",
    "予定": "Dự định, kế hoạch",
    "ガイドブック": "Sách hướng dẫn du lịch",
    "カレンダー": "Tờ lịch, cuốn lịch",
    "ポスター": "Áp phích quảng cáo, Poster",
    "予定表": "Bảng lịch trình, thời gian biểu",
    "ごみ箱": "Thùng rác",
    "人形": "Búp bê",
    "花瓶": "Bình hoa, lọ hoa",
    "鏡": "Cái gương",
    "引き出し": "Ngăn kéo tủ",
    "玄関": "Cửa vào, sảnh trước hiên nhà",
    "廊下": "Hành lang",
    "池": "Cái ao, hồ nước nhỏ",
    "元の 所": "Chỗ cũ, vị trí ban đầu",
    "周り": "Xung quanh",
    "真ん中": "Chính giữa, trung tâm",
    "隅": "Góc (trong căn phòng)",
    "リュック": "Ba lô",
    "非常袋": "Túi đồ khẩn cấp, túi cứu nạn",
    "非常時": "Lúc khẩn cấp, thời điểm nguy cấp",
    "生活します": "Sinh sống",
    "懐中電灯": "Đèn pin",
    "～とか、～とか": "Nào là ~, nào là ~",
    "丸い": "Tròn, hình tròn",
    "ある ～": "Một ~ nọ, có một ~",
    "夢を 見ます": "Mơ thấy giấc mơ",
    "うれしい": "Vui sướng, mừng rỡ",
    "嫌［な］": "Khó chịu, ghét, không thích",
    "すると": "Thế là, ngay lập tức thì",
    "目が 覚めます": "Tỉnh giấc, mở mắt dậy",
    "片付けます": "Dọn dẹp ngăn nắp",
    "相談します": "Thảo luận, trao đổi, bàn bạc",
    "お苦労さま。": "Anh/chị đã vất vả rồi (cấp trên nói với cấp dưới).",
    "ご苦労さま。": "Anh/chị đã vất vả rồi (cấp trên nói với cấp dưới).",
    "希望": "Nguyện vọng, mong muốn",
    "何か ご希望が ありますか。": "Quý khách có yêu cầu/nguyện vọng gì không ạ?",
    "ミュージカル": "Ca kịch, nhạc kịch (Musical)",
    "それは いいですね。": "Ý kiến đó hay đấy nhỉ!",
}

def clean_meaning_str(text):
    if not text:
        return ""
    import re
    t = re.sub(r"#.*$", "", text).strip()
    t = t.strip("\"'“””")
    t = t.rstrip(",").strip()
    return t

def apply_part3():
    file_path = "src/data/minna_lessons.json"
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    updated = 0
    for lesson in data:
        if 21 <= lesson.get("lesson") <= 30:
            for w in lesson.get("words", []):
                k = (w.get("kanji") or "").strip()
                kn = (w.get("kana") or "").strip()
                clean_en = clean_meaning_str(w.get("meaning_en", ""))
                w["meaning_en"] = clean_en
                # Match
                for dict_key, correct_m in MINNA_LESSONS_21_30.items():
                    if k == dict_key or kn == dict_key or k.replace(" ", "") == dict_key.replace(" ", ""):
                        w["meaning"] = correct_m
                        updated += 1
                        break

    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"-> Hoàn tất chuẩn hóa Bài 21 - 30: Cập nhật {updated} từ!")

if __name__ == "__main__":
    apply_part3()
