# -*- coding: utf-8 -*-
"""
Minna no Nihongo - Chuẩn hóa Bài 1 đến Bài 10 theo Sách Giáo Trình tiếng Việt chính thức.
"""
import json
import sys
import os

sys.stdout.reconfigure(encoding='utf-8')

MINNA_LESSONS_1_10 = {
    # --- BÀI 1 ---
    "わたし": "Tôi",
    "わたしたち": "Chúng tôi, chúng ta",
    "あなた": "Bạn, anh, chị (ngôi thứ 2)",
    "あの人": "Người kia, người đó",
    "あの方": "Vị kia (cách nói lịch sự của あの人)",
    "皆さん": "Các bạn, mọi người",
    "～さん": "Anh, chị, ông, bà (hậu tố lịch sự sau tên)",
    "～ちゃん": "Bé (hậu tố gọi thân mật cho trẻ em/bạn gái)",
    "～君": "Cậu, bạn (hậu tố gọi thân mật cho bé trai/bạn nam)",
    "～人": "Người (nước ~)",
    "先生": "Thầy, cô giáo (không dùng khi nói về nghề của mình)",
    "教師": "Giáo viên, giảng viên (dùng khi nói về nghề nghiệp)",
    "学生": "Học sinh, sinh viên",
    "会社員": "Nhân viên công ty",
    "社員": "Nhân viên của công ty ~ (dùng kèm tên công ty)",
    "銀行員": "Nhân viên ngân hàng",
    "医者": "Bác sĩ",
    "研究者": "Nhà nghiên cứu",
    "エンジニア": "Kỹ sư",
    "大学": "Trường đại học",
    "病院": "Bệnh viện",
    "電気": "Điện, đèn điện",
    "だれ": "Ai (nghi vấn từ thông thường)",
    "どなた": "Vị nào (cách nói lịch sự của だれ)",
    "－歳": "Tuổi",
    "何歳": "Mấy tuổi, bao nhiêu tuổi",
    "おいくつ": "Bao nhiêu tuổi (lịch sự của なんさい)",
    "はい": "Vâng, dạ, đúng vậy",
    "いいえ": "Không, không phải",
    "初めまして。": "Rất hân hạnh được làm quen (chào lần đầu gặp)",
    "～から 来ました。": "Tôi đến từ...",
    "［どうぞ］よろしく［お願いします］。": "Rất mong nhận được sự giúp đỡ của anh/chị",
    "失礼ですが": "Xin lỗi cho tôi hỏi... (mở đầu khi hỏi thông tin cá nhân)",
    "お名前は？": "Tên anh/chị là gì ạ?",
    "こちらは ～さんです。": "Đây là anh/chị...",
    "アメリカ": "Nước Mỹ",
    "イギリス": "Nước Anh",
    "インド": "Nước Ấn Độ",
    "インドネシア": "Nước Indonesia",
    "韓国": "Hàn Quốc",
    "タイ": "Thái Lan",
    "中国": "Trung Quốc",
    "ドイツ": "Nước Đức",
    "日本": "Nhật Bản",
    "ブラジル": "Braxin",
    "フランス": "Nước Pháp",

    # --- BÀI 2 ---
    "これ": "Cái này (gần người nói)",
    "それ": "Cái đó (gần người nghe)",
    "あれ": "Cái kia (xa cả hai người)",
    "この ～": "Này (~ đứng trước danh từ)",
    "その ～": "Đó (~ đứng trước danh từ)",
    "あの ～": "Kia (~ đứng trước danh từ)",
    "本": "Sách",
    "辞書": "Từ điển",
    "雑誌": "Tạp chí",
    "新聞": "Báo, tờ báo",
    "ノート": "Vở, sổ tay",
    "手帳": "Sổ tay cá nhân",
    "名刺": "Danh thiếp",
    "カード": "Thẻ, cạc",
    "鉛筆": "Bút chì",
    "ボールペン": "Bút bi",
    "シャープペンシル": "Bút chì kim",
    "かぎ": "Chìa khóa",
    "時計": "Đồng hồ",
    "傘": "Ô, dù",
    "かばん": "Cặp sách, túi xách",
    "CD": "Đĩa CD",
    "テレビ": "Ti vi",
    "ラジオ": "Đài radio",
    "カメラ": "Máy ảnh",
    "コンピューター": "Máy vi tính",
    "車": "Xe hơi, ô tô",
    "自動車": "Xe ô tô",
    "机": "Bàn học, bàn làm việc",
    "いす": "Ghế",
    "チョコレート": "Sô-cô-la",
    "コーヒー": "Cà phê",
    "［お］土産": "Quà lưu niệm",
    "英語": "Tiếng Anh",
    "日本語": "Tiếng Nhật",
    "～語": "Tiếng (ngôn ngữ ~)",
    "何": "Cái gì",
    "そう": "Đúng vậy",
    "あのう": "À, ừm (ngập ngừng khi bắt đầu nói)",
    "えっ": "Ồ? Cái gì cơ! (ngạc nhiên)",
    "どうぞ。": "Xin mời.",
    "［どうも］ありがとう［ございます］。": "Xin chân thành cảm ơn [rất nhiều].",
    "そうですか。": "Thế à? / Ra là vậy.",
    "違います。": "Không phải, sai rồi.",
    "あ": "A, Ôi (thốt lên khi nhận ra điều gì)",
    "これから お世話に なります。": "Từ nay rất mong được sự giúp đỡ của anh/chị.",
    "こちらこそ［どうぞ］よろしく［お願いします］。": "Chính tôi mới là người mong được sự giúp đỡ ạ.",
    "テレホンカード": "Thẻ điện thoại",
    "［カセット］テープ": "Băng cát-sét",
    "テープレコーダー": "Máy ghi âm",
    "ほんの 気持ちです。": "Chút lòng thành của tôi.",
    "どうも。": "Cảm ơn.",

    # --- BÀI 3 ---
    "ここ": "Chỗ này, đây (gần người nói)",
    "そこ": "Chỗ đó, đấy (gần người nghe)",
    "あそこ": "Chỗ kia, đằng kia (xa cả hai)",
    "どこ": "Ở đâu",
    "こちら": "Phía này, hướng này (lịch sự của ここ)",
    "そちら": "Phía đó, hướng đó (lịch sự của そこ)",
    "あちら": "Phía kia, hướng kia (lịch sự của あそこ)",
    "どちら": "Phía nào, hướng nào (lịch sự của どこ)",
    "教室": "Phòng học, lớp học",
    "食堂": "Nhà ăn, căng tin",
    "事務所": "Văn phòng làm việc",
    "会議室": "Phòng họp",
    "受付": "Quầy tiếp tân",
    "ロビー": "Sảnh chờ",
    "部屋": "Căn phòng",
    "トイレ": "Nhà vệ sinh",
    "お手洗い": "Phòng vệ sinh (cách nói lịch sự)",
    "階段": "Cầu thang bộ",
    "エレベーター": "Thang máy",
    "エスカレーター": "Thang cuốn",
    "自動販売機": "Máy bán hàng tự động",
    "電話": "Điện thoại, cuộc gọi",
    "［お］国": "Đất nước, quốc gia",
    "会社": "Công ty",
    "うち": "Nhà (của mình)",
    "靴": "Giày dép",
    "ネクタイ": "Cà vạt",
    "ワイン": "Rượu vang",
    "売り場": "Quầy bán hàng",
    "地下": "Tầng hầm",
    "－階": "Tầng",
    "何階": "Tầng mấy",
    "－円": "Yên Nhật",
    "いくら": "Bao nhiêu tiền",
    "百": "Trăm",
    "千": "Nghìn",
    "万": "Mười nghìn (vạn)",
    "すみません。": "Xin lỗi.",
    "いらっしゃいませ。": "Kính chào quý khách! (lời chào khi khách vào quán)",
    "［～を］見せて ください。": "Xin cho tôi xem [～].",
    "じゃ": "Thế thì, vậy thì",
    "［～を］ください。": "Làm ơn bán/cho tôi [～].",
    "イタリア": "Nước Ý",
    "スイス": "Thụy Sĩ",
    "たばこ": "Thuốc lá",
    "～で ございます。": "Là, thì (cách nói trang trọng lịch sự của です)",

    # --- BÀI 4 ---
    "起きます": "Thức dậy",
    "寝ます": "Ngủ, đi ngủ",
    "働きます": "Làm việc",
    "休みます": "Nghỉ, nghỉ ngơi",
    "勉強します": "Học, học tập",
    "終わります": "Kết thúc, xong",
    "デパート": "Trung tâm thương mại, bách hóa",
    "銀行": "Ngân hàng",
    "郵便局": "Bưu điện",
    "図書館": "Thư viện",
    "美術館": "Bảo tàng mỹ thuật",
    "今": "Bây giờ",
    "－時": "Giờ",
    "－分": "Phút",
    "半": "Rưỡi, nửa (30 phút)",
    "何時": "Mấy giờ",
    "何分": "Mấy phút",
    "午前": "Buổi sáng (AM)",
    "午後": "Buổi chiều (PM)",
    "朝": "Buổi sáng",
    "昼": "Buổi trưa",
    "晩": "Buổi tối",
    "夜": "Ban đêm, buổi tối",
    "おととい": "Hôm kia",
    "きのう": "Hôm qua",
    "きょう": "Hôm nay",
    "あした": "Ngày mai",
    "あさって": "Ngày kìa",
    "けさ": "Sáng nay",
    "今晩": "Tối nay",
    "休み": "Nghỉ ngơi, ngày nghỉ",
    "昼休み": "Nghỉ trưa",
    "試験": "Bài thi, kỳ thi",
    "会議": "Cuộc họp",
    "映画": "Bộ phim",
    "毎朝": "Mỗi sáng",
    "毎晩": "Mỗi tối",
    "毎日": "Mỗi ngày",
    "月曜日": "Thứ hai",
    "火曜日": "Thứ ba",
    "水曜日": "Thứ tư",
    "木曜日": "Thứ năm",
    "金曜日": "Thứ sáu",
    "土曜日": "Thứ bảy",
    "日曜日": "Chủ nhật",
    "何曜日": "Thứ mấy",
    "～から": "Từ...",
    "～まで": "Đến...",
    "～と ～": "Và, với (nối hai danh từ)",
    "大変ですね。": "Vất vả quá nhỉ / Khổ thân anh/chị nhỉ.",
    "番号": "Số điện thoại, số hiệu",
    "何番": "Số mấy, số bao nhiêu",
    "えーと": "À, để tôi xem... (ngập ngừng khi suy nghĩ)",
    "お願い します。": "Làm ơn / Nhờ anh/chị giúp đỡ.",
    "かしこまりました。": "Tôi hiểu rồi ạ / Vâng, được rồi ạ (kính ngữ tiếp khách)",
    "お問い合わせの番号": "Số điện thoại mà quý khách cần hỏi",
    "［どうも］ありがとう ございました。": "Xin chân thành cảm ơn anh/chị.",

    # --- BÀI 5 ---
    "行きます": "Đi",
    "来ます": "Đến",
    "帰ります": "Về, trở về",
    "学校": "Trường học",
    "スーパー": "Siêu thị",
    "駅": "Nhà ga",
    "飛行機": "Máy bay",
    "船": "Tàu thủy, thuyền",
    "電車": "Tàu điện",
    "地下鉄": "Tàu điện ngầm",
    "新幹線": "Tàu siêu tốc Shinkansen",
    "バス": "Xe buýt",
    "タクシー": "Xe taxi",
    "自転車": "Xe đạp",
    "歩いて": "Đi bộ",
    "人": "Người",
    "友達": "Bạn bè",
    "彼": "Anh ấy, bạn trai",
    "彼女": "Cô ấy, bạn gái",
    "家族": "Gia đình",
    "一人で": "Một mình",
    "先週": "Tuần trước",
    "今週": "Tuần này",
    "来週": "Tuần sau",
    "先月": "Tháng trước",
    "今月": "Tháng này",
    "来月": "Tháng sau",
    "去年": "Năm ngoái",
    "ことし": "Năm nay",
    "今年": "Năm nay",
    "来年": "Năm sau",
    "－年": "Năm",
    "何年": "Năm nào, mấy năm",
    "－月": "Tháng",
    "何月": "Tháng mấy",
    "１日": "Mùng 1 (ngày mùng 1)",
    "２日": "Mùng 2, hai ngày",
    "３日": "Mùng 3, ba ngày",
    "４日": "Mùng 4, bốn ngày",
    "５日": "Mùng 5, năm ngày",
    "６日": "Mùng 6, sáu ngày",
    "７日": "Mùng 7, bảy ngày",
    "８日": "Mùng 8, tám ngày",
    "９日": "Mùng 9, chín ngày",
    "１０日": "Mùng 10, mười ngày",
    "１４日": "Mùng 14, mười bốn ngày",
    "２０日": "Ngày 20, hai mươi ngày",
    "２４日": "Ngày 24, hai mươi tư ngày",
    "－日": "Ngày (số ngày / ngày trong tháng)",
    "何日": "Mấy ngày, ngày mấy",
    "いつ": "Khi nào, bao giờ",
    "誕生日": "Sinh nhật",
    "そうですね。": "Đúng thế nhỉ / Để tôi xem nào...",
    "どう いたしまして。": "Không có chi, đừng bận tâm.",
    "－番線": "Sân ga số -, đường tàu số -",
    "次の": "Tiếp theo, kế tiếp",
    "普通": "Tàu thường (dừng ở tất cả các ga)",
    "急行": "Tàu tốc hành",
    "特急": "Tàu tốc hành đặc biệt (Limited Express)",
    "大阪城": "Lâu đài Osaka",

    # --- BÀI 6 ---
    "食べます": "Ăn",
    "飲みます": "Uống",
    "吸います［たばこを～］": "Hút [thuốc lá]",
    "見ます": "Xem, nhìn",
    "聞きます": "Nghe",
    "読みます": "Đọc",
    "書きます": "Viết, vẽ",
    "買います": "Mua",
    "撮ります［写真を～］": "Chụp [ảnh]",
    "します": "Làm, chơi",
    "会います［友達に～］": "Gặp [bạn bè]",
    "ごはん": "Cơm, bữa ăn",
    "朝ごはん": "Bữa sáng",
    "昼ごはん": "Bữa trưa",
    "晩ごはん": "Bữa tối",
    "パン": "Bánh mì",
    "卵": "Trứng",
    "肉": "Thịt",
    "魚": "Cá",
    "野菜": "Rau",
    "果物": "Hoa quả, trái cây",
    "水": "Nước",
    "お茶": "Trà, chè xanh",
    "紅茶": "Trà đen, hồng trà",
    "牛乳": "Sữa bò",
    "ミルク": "Sữa",
    "ジュース": "Nước hoa quả",
    "ビール": "Bia",
    "［お］酒": "Rượu, rượu sake",
    "手紙": "Lá thư",
    "レポート": "Báo cáo",
    "写真": "Bức ảnh",
    "ビデオ": "Băng video, video",
    "店": "Cửa hàng, tiệm",
    "庭": "Khu vườn",
    "宿題": "Bài tập về nhà",
    "テニス": "Quần vợt, tennis",
    "サッカー": "Bóng đá",
    "［お］花見": "Ngắm hoa anh đào",
    "いっしょに": "Cùng nhau",
    "ちょっと": "Một chút, một lát",
    "いつも": "Lúc nào cũng, luôn luôn",
    "時々": "Thỉnh thoảng, đôi khi",
    "それから": "Sau đó, tiếp theo",
    "ええ": "Vâng, ừ",
    "いいですね。": "Được đấy nhỉ / Hay quá nhỉ.",
    "わかりました。": "Tôi hiểu rồi / Đã rõ.",
    "何ですか。": "Có chuyện gì thế? / Vâng, sao ạ?",
    "じゃ、また［あした］。": "Hẹn gặp lại [ngày mai] nhé.",

    # --- BÀI 7 ---
    "切ります": "Cắt, gọt",
    "送ります": "Gửi",
    "あげます": "Cho, tặng",
    "もらいます": "Nhận",
    "貸します": "Cho mượn, cho vay",
    "借ります": "Mượn, vay",
    "教えます": "Dạy, chỉ bảo",
    "習います": "Học tập (từ ai đó)",
    "かけます［電話を～］": "Gọi [điện thoại]",
    "手": "Tay, bàn tay",
    "はし": "Đũa",
    "スプーン": "Thìa, muỗng",
    "ナイフ": "Dao",
    "フォーク": "Nĩa, dĩa",
    "はさみ": "Kéo",
    "パソコン": "Máy vi tính cá nhân",
    "ケータイ": "Điện thoại di động",
    "メール": "Thư điện tử, email",
    "年賀状": "Thiệp chúc tết",
    "パンチ": "Cái bấm lỗ",
    "ホッチキス": "Cái dập ghim",
    "セロテープ": "Băng dính",
    "消しゴム": "Cục tẩy",
    "紙": "Tờ giấy",
    "花": "Bông hoa",
    "シャツ": "Áo sơ mi",
    "プレゼント": "Món quà",
    "荷物": "Hành lý, bưu phẩm",
    "お金": "Tiền bạc",
    "切符": "Vé (tàu, xe)",
    "クリスマス": "Giáng sinh",
    "父": "Bố (của mình)",
    "母": "Mẹ (của mình)",
    "お父さん": "Bố (của người khác)",
    "お母さん": "Mẹ (của người khác)",
    "もう": "Đã, rồi",
    "まだ": "Chưa",
    "これから": "Từ bây giờ, sau đây",
    "［～、］すてきですね。": "[~] đẹp thật đấy nhỉ / Tuyệt quá nhỉ.",
    "いらっしゃい。": "Chào mừng bạn đến chơi!",
    "どうぞ お上がり ください。": "Xin mời anh/chị vào nhà.",
    "失礼します。": "Xin phép (khi vào phòng/ra về)",
    "［～は］いかがですか。": "Anh/chị dùng [～] có được không?",
    "いただきます。": "Tôi xin phép nhận / Mời mọi người dùng bữa.",
    "ごちそうさま［でした］。": "Cảm ơn vì bữa ăn ngon.",
    "ごめんください。": "Xin lỗi, có ai ở nhà không? (khi đến thăm nhà)",

    # --- BÀI 8 ---
    "ハンサム［な］": "Đẹp trai",
    "きれい［な］": "Đẹp, sạch sẽ",
    "静か［な］": "Yên tĩnh",
    "にぎやか［な］": "Náo nhiệt, nhộn nhịp",
    "有名［な］": "Nổi tiếng",
    "親切［な］": "Tốt bụng, thân thiện",
    "元気［な］": "Khỏe mạnh",
    "暇［な］": "Rảnh rỗi",
    "便利［な］": "Tiện lợi, thuận tiện",
    "すてき［な］": "Đẹp, tuyệt vời",
    "大きい": "Lớn, to",
    "小さい": "Nhỏ, bé",
    "新しい": "Mới",
    "古い": "Cũ, cổ",
    "いい": "Tốt, hay",
    "よい": "Tốt, hay (thể chia)",
    "悪い": "Xấu, tồi",
    "暑い、熱い": "Nóng (thời tiết / nhiệt độ)",
    "寒い": "Lạnh (thời tiết)",
    "冷たい": "Lạnh, buốt (cảm giác đồ vật)",
    "難しい": "Khó khăn",
    "易しい": "Dễ dàng",
    "高い": "Cao, đắt",
    "安い": "Rẻ",
    "低い": "Thấp",
    "おもしろい": "Thú vị, hay",
    "おいしい": "Ngon miệng",
    "忙しい": "Bận rộn",
    "楽しい": "Vui vẻ",
    "白い": "Trắng",
    "黒い": "Đen",
    "赤い": "Đỏ",
    "青い": "Xanh da trời",
    "桜": "Hoa anh đào",
    "山": "Ngọn núi",
    "町": "Thị trấn, thành phố",
    "食べ物": "Đồ ăn, thức ăn",
    "所": "Nơi chốn, địa điểm",
    "寮": "Ký túc xá",
    "生活": "Cuộc sống, sinh hoạt",
    "［お］仕事": "Công việc",
    "どう": "Thế nào, như thế nào",
    "どんな ～": "Như thế nào (~ đứng trước danh từ)",
    "どれ": "Cái nào",
    "とても": "Rất",
    "あまり": "Không... lắm (đi với phủ định)",
    "そして": "Và, hơn nữa",
    "～が、～": "...nhưng...",
    "お元気ですか。": "Bạn có khỏe không?",
    "日本の 生活に 慣れましたか。": "Bạn đã quen với cuộc sống ở Nhật chưa?",
    "［～、］もう 一杯 いかがですか。": "Bạn dùng thêm một cốc [～] nữa nhé?",
    "もう ～です［ね］。": "Đã ～ rồi [nhỉ].",
    "そろそろ 失礼します。": "Đã đến lúc tôi phải xin phép về.",
    "また いらっしゃって ください。": "Lần sau bạn lại ghé chơi nhé.",

    # --- BÀI 9 ---
    "わかります": "Hiểu, nắm rõ",
    "あります": "Có (sở hữu/tồn tại đồ vật)",
    "好き［な］": "Thích",
    "嫌い［な］": "Ghét, không thích",
    "上手［な］": "Giỏi, khéo",
    "下手［な］": "Kém, dở",
    "飲み物": "Đồ uống",
    "料理": "Món ăn, nấu ăn",
    "スポーツ": "Thể thao",
    "野球": "Bóng chày",
    "ダンス": "Khiêu vũ, nhảy múa",
    "旅行": "Du lịch, chuyến đi",
    "音楽": "Âm nhạc",
    "歌": "Bài hát",
    "クラシック": "Nhạc cổ điển",
    "ジャズ": "Nhạc jazz",
    "コンサート": "Buổi hòa nhạc",
    "カラオケ": "Hát karaoke",
    "歌舞伎": "Kịch Kabuki truyền thống",
    "絵": "Bức tranh, hội họa",
    "字": "Chữ cái, chữ viết",
    "漢字": "Chữ Hán",
    "ひらがな": "Chữ cái Hiragana",
    "かたかな": "Chữ cái Katakana",
    "ローマ字": "Chữ cái La Mã (Romaji)",
    "細かい お金": "Tiền lẻ",
    "チケット": "Vé",
    "時間": "Thời gian",
    "用事": "Việc bận",
    "約束": "Lời hẹn, cuộc hẹn",
    "アルバイト": "Công việc làm thêm",
    "ご主人": "Chồng (người khác)",
    "夫": "Chồng (của mình)",
    "主人": "Chồng (của mình)",
    "奥さん": "Vợ (người khác)",
    "妻": "Vợ (của mình)",
    "家内": "Vợ (của mình)",
    "子ども": "Con cái, trẻ con",
    "よく": "Rõ ràng, thường xuyên",
    "だいたい": "Đại khái, khoảng",
    "たくさん": "Nhiều",
    "少し": "Một ít, một chút",
    "全然": "Hoàn toàn không (đi với phủ định)",
    "早く、速く": "Sớm, nhanh",
    "どうして": "Tại sao, vì sao",
    "残念です［ね］。": "Thật đáng tiếc nhỉ.",
    "もしもし": "Alo (nghe điện thoại)",
    "ああ": "A, ồ (thán từ)",
    "いっしょに いかがですか。": "Bạn tham gia cùng chúng tôi nhé?",
    "［～は］ちょっと…": "[～ thì] hơi kẹt / khó rồi...",
    "だめですか。": "Không được sao?",
    "また 今度 お願いします。": "Hẹn bạn lần sau vậy nhé.",

    # --- BÀI 10 ---
    "います": "Có, ở (người, động vật sống)",
    "いろいろ［な］": "Nhiều, phong phú, đa dạng",
    "男の 人": "Người đàn ông",
    "女の 人": "Người phụ nữ",
    "男の 子": "Cậu bé, bé trai",
    "女の 子": "Cô bé, bé gái",
    "犬": "Con chó",
    "猫": "Con mèo",
    "パンダ": "Gấu trúc",
    "象": "Con voi",
    "木": "Cây cối, gỗ",
    "物": "Đồ vật",
    "電池": "Pin",
    "箱": "Cái hộp, thùng",
    "スイッチ": "Công tắc điện",
    "冷蔵庫": "Tủ lạnh",
    "テーブル": "Bàn ăn",
    "ベッド": "Giường ngủ",
    "棚": "Giá sách, kệ tủ",
    "ドア": "Cửa ra vào",
    "窓": "Cửa sổ",
    "ポスト": "Hộp thư",
    "ビル": "Tòa nhà cao tầng",
    "ATM": "Cây rút tiền ATM",
    "コンビニ": "Cửa hàng tiện lợi",
    "公園": "Công viên",
    "喫茶店": "Quán cà phê, quán giải khát",
    "～屋": "Cửa hàng bán...",
    "乗り場": "Điểm đón xe, bến xe",
    "県": "Tỉnh (đơn vị hành chính)",
    "上": "Trên",
    "下": "Dưới",
    "前": "Trước",
    "後ろ": "Sau",
    "右": "Bên phải",
    "左": "Bên trái",
    "中": "Bên trong",
    "外": "Bên ngoài",
    "隣": "Bên cạnh",
    "近く": "Gần",
    "間": "Ở giữa",
    "～や～［など］": "...và... [vân vân]",
    "東京ディズニーランド": "Công viên Tokyo Disneyland",
    "チリソース": "Tương ớt",
    "奥": "Bên trong cùng, góc sâu bên trong",
    "スパイスコーナー": "Góc bày gia vị"
}

def clean_meaning_str(text):
    if not text:
        return ""
    import re
    t = re.sub(r"#.*$", "", text).strip()
    t = t.strip("\"'“””")
    t = t.rstrip(",").strip()
    return t

def apply_part1():
    file_path = "src/data/minna_lessons.json"
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    updated = 0
    for lesson in data:
        if lesson.get("lesson") <= 10:
            for w in lesson.get("words", []):
                k = (w.get("kanji") or "").strip()
                kn = (w.get("kana") or "").strip()
                clean_en = clean_meaning_str(w.get("meaning_en", ""))
                w["meaning_en"] = clean_en
                # Match
                for dict_key, correct_m in MINNA_LESSONS_1_10.items():
                    if k == dict_key or kn == dict_key or k.replace(" ", "") == dict_key.replace(" ", ""):
                        w["meaning"] = correct_m
                        updated += 1
                        break

    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"-> Hoàn tất chuẩn hóa Bài 1 - 10: Cập nhật {updated} từ!")

if __name__ == "__main__":
    apply_part1()
